import { internalMutation, internalQuery } from "./_generated/server";
import type { Doc, Id } from "./_generated/dataModel";
import { v } from "convex/values";
import { recordGranted, requireAgent, type Principal } from "./identity";
import { fail } from "./errors";
import { applyChange } from "./lib/applyChange";
import { listRecords as listRecordPage } from "./lib/list";
import { readable, readableMap, resolveValues } from "./lib/values";
import { canPropose, canReadObject, canReadRecordId, canReadRecord, canReadField, requireObjectRead, requireRecordRead, requireQueryField, visibleTitle, projectEvent } from "./authority/reads";
import { writable } from "./authority/readonly";
import { canSeeInbox, visibleInbox } from "./authority/inbox";

const keyHash = v.string();
const action = v.union(v.literal("create"), v.literal("update"), v.literal("delete"));
const status = v.union(v.literal("pending"), v.literal("applied"), v.literal("dismissed"), v.literal("conflicted"));
const inboxStatus = v.union(v.literal("pending"), v.literal("resolved"));

async function objectFor(ctx: any, orgId: Id<"orgs">, key: string): Promise<{ object: Doc<"objects">; fields: Doc<"fields">[] }> {
  const object = await ctx.db.query("objects").withIndex("by_org_key", (q: any) => q.eq("orgId", orgId).eq("key", key)).unique() as Doc<"objects"> | null;
  if (!object) fail("NOT_FOUND", "Object not found");
  const fields = await ctx.db.query("fields").withIndex("by_object", (q: any) => q.eq("orgId", orgId).eq("objectId", object._id)).collect() as Doc<"fields">[];
  return { object, fields: fields.filter((field: Doc<"fields">) => !field.retired).sort((a: Doc<"fields">, b: Doc<"fields">) => a.order - b.order) };
}
async function objectForId(ctx: any, orgId: Id<"orgs">, objectId: Id<"objects">) {
  const object = await ctx.db.get(objectId) as Doc<"objects"> | null;
  if (!object || object.orgId !== orgId) fail("NOT_FOUND", "Object not found");
  return objectFor(ctx, orgId, object.key);
}

async function recordFor(ctx: any, orgId: Id<"orgs">, idOrRef: string): Promise<Doc<"records">> {
  const id = ctx.db.normalizeId("records", idOrRef);
  const record = ((id && await ctx.db.get(id)) ?? await ctx.db.query("records").withIndex("by_org_ref", (q: any) => q.eq("orgId", orgId).eq("ref", idOrRef.trim().toLowerCase())).unique()) as Doc<"records"> | null;
  if (!record || record.orgId !== orgId) fail("NOT_FOUND", "Record not found");
  return record;
}

async function suggestionApi(ctx: any, principal: Principal, suggestion: Doc<"suggestions">) {
  const orgId = principal.org._id;
  const sourceObject = await ctx.db.get(suggestion.change.objectId) as Doc<"objects"> | null;
  const { object, fields } = await objectFor(ctx, orgId, sourceObject?.key ?? "");
  const record = suggestion.change.recordId ? await ctx.db.get(suggestion.change.recordId) : null, agent = await ctx.db.get(suggestion.agentId);
  requireObjectRead(principal, object);
  if (!canReadRecordId(principal, object, suggestion.change.recordId)) fail("NOT_FOUND", "Suggestion not found");
  const visible = fields.filter(f => canReadField(principal, object, f, suggestion.change.recordId));
  const byId = new Map(visible.map((field: Doc<"fields">) => [field._id as string, field]));
  const conflicts = suggestion.conflicts ? await Promise.all(suggestion.conflicts.filter(conflict => byId.has(conflict.fieldId)).map(async (conflict) => { const field = byId.get(conflict.fieldId); const show = async (value: unknown) => field ? (await readableMap(ctx, principal, visible, { [field._id]: value }))[field.key] : value; return { field: field?.key ?? conflict.fieldId, expected: await show(conflict.expected), actual: await show(conflict.actual) }; })) : undefined;
  return { id: suggestion._id, status: suggestion.status, action: suggestion.change.action, object: object.key, record: record ? { id: record._id, ref: record.ref ?? null, title: await visibleTitle(ctx, principal, record) } : null, values: await readableMap(ctx, principal, visible, suggestion.change.values), before: await readableMap(ctx, principal, visible, suggestion.before), reason: visible.length === fields.length ? suggestion.reason : "", agent: agent?.name ?? null, createdAt: suggestion._creationTime, resolvedAt: suggestion.resolvedAt ?? null, ...(conflicts ? { conflicts } : {}) };
}

export const me = internalQuery({ args: { keyHash }, handler: async (ctx, args) => { const principal = await requireAgent(ctx, args.keyHash); const [pendingInbox, pendingSuggestions] = await Promise.all([ctx.db.query("agentInbox").withIndex("by_org_status", (q) => q.eq("orgId", principal.org._id).eq("status", "pending")).collect(), ctx.db.query("suggestions").withIndex("by_org_status", (q) => q.eq("orgId", principal.org._id).eq("status", "pending")).collect()]); return { org: { id: principal.org._id, name: principal.org.name }, agent: { id: principal.agent._id, name: principal.agent.name, role: principal.agent.role, grants: principal.agent.grants }, pendingInbox: pendingInbox.filter(item => canSeeInbox(principal, item)).length, pendingSuggestions: (await Promise.all(pendingSuggestions.map(async suggestion => { const object = await ctx.db.get(suggestion.change.objectId); return object && canReadRecordId(principal, object, suggestion.change.recordId); }))).filter(Boolean).length }; } });
export const objects = internalQuery({ args: { keyHash }, handler: async (ctx, args) => { const principal = await requireAgent(ctx, args.keyHash), objects = await ctx.db.query("objects").withIndex("by_org", (q) => q.eq("orgId", principal.org._id)).collect(); return Promise.all(objects.filter(object => canReadObject(principal, object)).sort((a, b) => a.order - b.order).map(async (object) => { const fields = (await ctx.db.query("fields").withIndex("by_object", (q) => q.eq("orgId", principal.org._id).eq("objectId", object._id)).collect()).filter((field) => !field.retired && canReadField(principal, object, field)).sort((a, b) => a.order - b.order); return { key: object.key, label: object.label, labelPlural: object.labelPlural, titleField: fields.find((field) => field._id === object.titleFieldId)?.key ?? null, fields: await Promise.all(fields.map(async (field) => ({ key: field.key, label: field.label, type: field.type, ...(field.options ? { options: field.options } : {}), ...(field.targetObjectId ? { target: (await ctx.db.get(field.targetObjectId))?.key } : {}), required: field.required, indexed: !!field.slot }))) }; })); } });
export const listRecords = internalQuery({ args: { keyHash, object: v.string(), cursor: v.optional(v.string()), limit: v.optional(v.number()), sort: v.optional(v.object({ field: v.string(), direction: v.union(v.literal("asc"), v.literal("desc")) })), filter: v.optional(v.object({ field: v.string(), value: v.any() })) }, handler: async (ctx, args) => {
  const principal = await requireAgent(ctx, args.keyHash), item = await objectFor(ctx, principal.org._id, args.object), byKey = new Map(item.fields.map((field) => [field.key, field]));
  requireObjectRead(principal, item.object);
  const sort = args.sort ? { fieldId: byKey.get(args.sort.field)?._id, direction: args.sort.direction } : undefined;
  const filterField = args.filter ? byKey.get(args.filter.field) : undefined;
  if ((args.sort && !sort?.fieldId) || (args.filter && !filterField)) fail("NOT_FOUND", "Field not found");
  if (sort?.fieldId) requireQueryField(principal, item.object, byKey.get(args.sort!.field)!);
  if (filterField) requireQueryField(principal, item.object, filterField);
  // Query strings arrive as text; the slot holds the field's real type, so the value is coerced like any agent input.
  const filter = args.filter && filterField ? { fieldId: filterField._id, value: (await resolveValues(ctx, principal, item.object, item.fields, { [filterField.key]: args.filter.value }))[filterField._id] } : undefined;
  const page = await listRecordPage(ctx, principal.org._id, item.object._id, { cursor: args.cursor ?? null, numItems: Math.min(Math.max(Math.floor(args.limit ?? 25) || 25, 1), 100) }, sort as any, filter as any);
  return { records: await Promise.all((page.page as Doc<"records">[]).filter(record => canReadRecord(principal, item.object, record)).map((record) => readable(ctx, principal, record, item.object, item.fields))), cursor: page.isDone ? null : page.continueCursor };
} });

export const getRecord = internalQuery({ args: { keyHash, idOrRef: v.string() }, handler: async (ctx, args) => { const principal = await requireAgent(ctx, args.keyHash), record = await recordFor(ctx, principal.org._id, args.idOrRef), item = await objectForId(ctx, principal.org._id, record.objectId); requireRecordRead(principal, item.object, record); const events = await ctx.db.query("events").withIndex("by_record", (q) => q.eq("orgId", principal.org._id).eq("recordId", record._id)).order("desc").take(20); const byId = new Map(item.fields.map((field) => [field._id, field.key])); return { record: await readable(ctx, principal, record, item.object, item.fields), events: await Promise.all(events.map(async (event) => { const actor = event.actor.kind === "agent" ? await ctx.db.get(event.actor.id as Id<"agents">) : event.actor.kind === "user" ? await ctx.db.get(event.actor.id as Id<"users">) : null; const masked = await projectEvent(ctx, principal, event); const convert = (values: Record<string, unknown> | null) => values && Object.fromEntries(Object.entries(values).map(([id, value]) => [byId.get(id as Id<"fields">) ?? id, value])); return { at: event._creationTime, actor: { kind: event.actor.kind, name: actor?.name ?? event.actor.kind }, action: event.action, before: convert(masked?.before ?? null), after: convert(masked?.after ?? null), reason: masked?.reason ?? null }; })) }; } });
export const search = internalQuery({ args: { keyHash, q: v.string(), object: v.optional(v.string()), limit: v.optional(v.number()) }, handler: async (ctx, args) => { const principal = await requireAgent(ctx, args.keyHash); const item = args.object ? await objectFor(ctx, principal.org._id, args.object) : null, limit = Math.min(args.limit ?? 10, 100), q = args.q.trim(); const records = q ? await ctx.db.query("records").withSearchIndex("search_title", (query) => { const base = query.search("title", q).eq("orgId", principal.org._id); return item ? base.eq("objectId", item.object._id) : base; }).take(limit) : item ? await ctx.db.query("records").withIndex("by_object_updated", (query) => query.eq("orgId", principal.org._id).eq("objectId", item.object._id)).order("desc").take(limit) : []; return (await Promise.all(records.map(async (record) => { const recordItem = item && record.objectId === item.object._id ? item : await objectForId(ctx, principal.org._id, record.objectId); if (!canReadRecord(principal, recordItem.object, record) || (q && !(await visibleTitle(ctx, principal, record)))) return null; return readable(ctx, principal, record, recordItem.object, recordItem.fields); }))).filter(Boolean); } });
export const related = internalQuery({ args: { keyHash, idOrRef: v.string(), field: v.string() }, handler: async (ctx, args) => { const principal = await requireAgent(ctx, args.keyHash), target = await recordFor(ctx, principal.org._id, args.idOrRef), [objectKey, fieldKey] = args.field.split("."); const targetObject = await ctx.db.get(target.objectId); if (!targetObject) fail("NOT_FOUND"); requireRecordRead(principal, targetObject, target); if (!objectKey || !fieldKey) fail("VALIDATION", "Field must be objectKey.fieldKey"); const item = await objectFor(ctx, principal.org._id, objectKey), field = item.fields.find((value) => value.key === fieldKey); requireObjectRead(principal, item.object); if (field) requireQueryField(principal, item.object, field); if (!field || (field.type !== "lookup" && field.type !== "links") || (field.targetObjectId && field.targetObjectId !== target.objectId)) fail("NOT_FOUND", "Field does not relate to record"); let rows: Doc<"records">[] = []; if (field.type === "links") { const links = await ctx.db.query("links").withIndex("by_to", (q) => q.eq("orgId", principal.org._id).eq("fieldId", field._id).eq("toRecordId", target._id)).take(100); rows = (await Promise.all(links.map((link) => ctx.db.get(link.fromRecordId)))).filter(Boolean) as Doc<"records">[]; } else { if (!field.slot) fail("UNINDEXED_FIELD", "Field is not indexed"); const name = `${field.slot.kind}${field.slot.index}`; rows = await (ctx.db.query("records") as any).withIndex(`by_${name}`, (q: any) => q.eq("orgId", principal.org._id).eq("objectId", item.object._id).eq(name, target._id)).take(100); } return Promise.all(rows.filter(record => canReadRecord(principal, item.object, record)).map((record) => readable(ctx, principal, record, item.object, item.fields))); } });
export const today = internalQuery({ args: { keyHash }, handler: async (ctx, args) => { const principal = await requireAgent(ctx, args.keyHash), now = new Date(), midnight = Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate()), day = 86400000; const task = await objectFor(ctx, principal.org._id, "task").catch(() => null), opportunity = await objectFor(ctx, principal.org._id, "opportunity").catch(() => null); const tasks: Doc<"records">[] = [], quiet: Doc<"records">[] = []; const due = task?.fields.find((field) => field.key === "dueDate"), done = task?.fields.find((field) => field.key === "done"); if (task && canReadObject(principal, task.object) && due?.slot && canReadField(principal, task.object, due) && (!done || canReadField(principal, task.object, done))) { const name = `${due.slot.kind}${due.slot.index}`, rows = await (ctx.db.query("records") as any).withIndex(`by_${name}`, (q: any) => q.eq("orgId", principal.org._id).eq("objectId", task.object._id).gt(name, 0).lt(name, midnight + 8 * day)).take(200); for (const record of rows) if (canReadRecord(principal, task.object, record) && canReadField(principal, task.object, due, record._id) && (!done || (canReadField(principal, task.object, done, record._id) && record.values[done._id] !== true))) tasks.push(record); } if (opportunity && canReadObject(principal, opportunity.object)) { const stage = opportunity.fields.find((field) => field.key === "stage"), rows = await ctx.db.query("records").withIndex("by_object_updated", (q) => q.eq("orgId", principal.org._id).eq("objectId", opportunity.object._id).lt("updatedAt", Date.now() - 14 * day)).take(200); for (const record of rows) { const value = stage ? record.values[stage._id] : undefined; if ((!stage || canReadField(principal, opportunity.object, stage, record._id)) && value !== "won" && value !== "lost" && canReadRecord(principal, opportunity.object, record)) quiet.push(record); if (quiet.length === 20) break; } } return { tasks: task ? await Promise.all(tasks.slice(0, 50).map((record) => readable(ctx, principal, record, task.object, task.fields))) : [], quiet: opportunity ? await Promise.all(quiet.map((record) => readable(ctx, principal, record, opportunity.object, opportunity.fields))) : [] }; } });

const isEmpty = (value: unknown) => value === null || value === undefined;

// Finds what a change targets before anything is resolved, so a grant can be
// refused, and a bad object or record reported, without touching values.
async function targetOf(ctx: any, orgId: Id<"orgs">, args: { action: "create" | "update" | "delete"; object?: string; record?: string; values?: Record<string, unknown> }) {
  if (args.action === "create") { if (!args.object || !args.values) fail("VALIDATION", "Create needs object and values"); return { item: await objectFor(ctx, orgId, args.object), record: null as Doc<"records"> | null }; }
  if (!args.record) fail("VALIDATION", "Change needs record");
  const record = await recordFor(ctx, orgId, args.record), item = await objectForId(ctx, orgId, record.objectId);
  if (args.object && args.object !== item.object.key) fail("NOT_FOUND", "Record does not match object");
  if (args.action === "update" && !args.values) fail("VALIDATION", "Update needs values");
  return { item, record };
}
// Resolves values and checks required fields now, so a suggestion a person
// cannot apply is refused at proposal time rather than at their tap.
async function proposed(ctx: any, principal: Principal, args: { action: "create" | "update" | "delete"; values?: Record<string, unknown> }, target: { item: { object: Doc<"objects">; fields: Doc<"fields">[] }; record: Doc<"records"> | null }) {
  const { item, record } = target;
  requireObjectRead(principal, item.object);
  if (record) requireRecordRead(principal, item.object, record);
  else if (!canReadRecordId(principal, item.object)) fail('FORBIDDEN', 'All-record scope required to create');
  const visible = item.fields.filter(field => canReadField(principal, item.object, field, record?._id));
  if (args.action === 'delete' && Object.keys(record!.values).some(id => !visible.some(field => field._id === id))) fail('VALIDATION', 'Deletion includes restricted fields');
  const values = args.action === "delete" ? {} : await resolveValues(ctx, principal, item.object, visible, args.values ?? {});
  for (const field of item.fields) if (field.required && (args.action === "create" || field._id in values) && isEmpty(values[field._id])) fail("VALIDATION", `${field.label} is required`, { fieldKey: field.key });
  const before = args.action === "create" ? {} : args.action === "delete" ? record!.values : Object.fromEntries(Object.keys(values).map((id) => [id, record!.values[id] ?? null]));
  return { item, record, values, before };
}
export const propose = internalMutation({ args: { keyHash, action, object: v.optional(v.string()), record: v.optional(v.string()), values: v.optional(v.record(v.string(), v.any())), reason: v.string(), inboxId: v.optional(v.id("agentInbox")) }, handler: async (ctx, args) => { const principal = await requireAgent(ctx, args.keyHash); await writable(ctx, principal.org._id); const result = await proposed(ctx, principal, args, await targetOf(ctx, principal.org._id, args)); if (!canPropose(principal, result.item.object, result.record?._id, Object.keys(args.action === "delete" ? result.before : result.values))) fail("FORBIDDEN", "Proposal scope required"); if (args.inboxId) { const inbox = await ctx.db.get(args.inboxId); if (!inbox || !canSeeInbox(principal, inbox)) fail("NOT_FOUND", "Inbox item not found"); } const id = await ctx.db.insert("suggestions", { orgId: principal.org._id, agentId: principal.agent._id, authorityEpoch: principal.agent.authorityEpoch ?? 0, status: "pending", change: { action: args.action, objectId: result.item.object._id, ...(result.record ? { recordId: result.record._id } : {}), values: result.values }, ...(result.record ? { recordId: result.record._id } : {}), before: result.before, reason: args.reason, ...(args.inboxId ? { inboxId: args.inboxId } : {}) }); return { suggestion: await suggestionApi(ctx, principal, await ctx.db.get(id) as Doc<"suggestions">) }; } });
export const change = internalMutation({ args: { keyHash, action, object: v.optional(v.string()), record: v.optional(v.string()), values: v.optional(v.record(v.string(), v.any())), reason: v.string() }, handler: async (ctx, args) => { const principal = await requireAgent(ctx, args.keyHash), target = await targetOf(ctx, principal.org._id, args); if (!recordGranted(principal, args.action, target.item.object, target.record?._id)) fail("FORBIDDEN", `No grant for ${args.action}:${target.item.object.key}. Propose it instead.`); const result = await proposed(ctx, principal, args, target); const change = args.action === "create" ? { action: "create" as const, orgId: principal.org._id, objectId: result.item.object._id, values: result.values, reason: args.reason } : args.action === "update" ? { action: "update" as const, orgId: principal.org._id, recordId: result.record!._id, values: result.values, reason: args.reason } : { action: "delete" as const, orgId: principal.org._id, recordId: result.record!._id, reason: args.reason }; const applied = await applyChange(ctx, principal, change); const record = args.action === "delete" ? null : await ctx.db.get(applied.recordId); return { record: record ? await readable(ctx, principal, record, result.item.object, result.item.fields) : null, eventId: applied.eventId }; } });

export const listSuggestions = internalQuery({ args: { keyHash, status: v.optional(status) }, handler: async (ctx, args) => { const principal = await requireAgent(ctx, args.keyHash), rows = await ctx.db.query("suggestions").withIndex("by_org_status", (q) => q.eq("orgId", principal.org._id).eq("status", args.status ?? "pending")).order("desc").take(100); const visible = []; for (const suggestion of rows) { const object = await ctx.db.get(suggestion.change.objectId); if (object && canReadRecordId(principal, object, suggestion.change.recordId)) visible.push(await suggestionApi(ctx, principal, suggestion)); } return visible; } });
async function inboxApi(ctx: any, principal: Principal, original: Doc<"agentInbox">) { const item = await visibleInbox(ctx, principal, original); if (!item) fail("NOT_FOUND", "Inbox item not found"); const source = item.from.kind === "agent" ? await ctx.db.get(item.from.id as Id<"agents">) : await ctx.db.get(item.from.id as Id<"users">); return { id: item._id, text: item.text, source: item.source, from: { kind: item.from.kind, name: source?.name ?? null }, status: item.status, createdAt: item._creationTime, resolvedAt: item.resolvedAt ?? null, note: item.note ?? null, suggestionId: item.suggestionId ?? null, recordId: item.recordId ?? null }; }
export const inbox = internalQuery({ args: { keyHash, status: v.optional(inboxStatus) }, handler: async (ctx, args) => { const principal = await requireAgent(ctx, args.keyHash), rows = await ctx.db.query("agentInbox").withIndex("by_org_status", (q) => q.eq("orgId", principal.org._id).eq("status", args.status ?? "pending")).order("asc").take(100); return Promise.all(rows.filter(item => canSeeInbox(principal, item)).map((item) => inboxApi(ctx, principal, item))); } });
export const inboxAdd = internalMutation({ args: { keyHash, text: v.string(), source: v.optional(v.string()) }, handler: async (ctx, args) => { const principal = await requireAgent(ctx, args.keyHash); await writable(ctx, principal.org._id); if (!args.text.trim()) fail("VALIDATION", "Inbox text is required"); const id = await ctx.db.insert("agentInbox", { orgId: principal.org._id, text: args.text.trim(), source: args.source ?? "api", from: { kind: "agent", id: principal.agent._id }, status: "pending", audience: "author" }); return inboxApi(ctx, principal, await ctx.db.get(id) as Doc<"agentInbox">); } });
export const inboxResolve = internalMutation({ args: { keyHash, id: v.id("agentInbox"), note: v.optional(v.string()), suggestionId: v.optional(v.id("suggestions")), recordId: v.optional(v.id("records")) }, handler: async (ctx, args) => { const principal = await requireAgent(ctx, args.keyHash), item = await ctx.db.get(args.id); await writable(ctx, principal.org._id); if (!item || !canSeeInbox(principal, item)) fail("NOT_FOUND", "Inbox item not found"); if (item.status !== "pending") fail("CONFLICT", "Already resolved"); if (args.suggestionId) { const suggestion = await ctx.db.get(args.suggestionId); const object = suggestion ? await ctx.db.get(suggestion.change.objectId) : null; if (!suggestion || !object || !canReadRecordId(principal, object, suggestion.change.recordId)) fail("NOT_FOUND", "Suggestion not found"); } if (args.recordId) { const record = await ctx.db.get(args.recordId); const object = record ? await ctx.db.get(record.objectId) : null; if (!record || !object || !canReadRecord(principal, object, record)) fail("NOT_FOUND", "Record not found"); } await ctx.db.patch(item._id, { status: "resolved", resolvedBy: principal.agent._id, resolvedAt: Date.now(), ...(args.note !== undefined ? { note: args.note } : {}), ...(args.suggestionId ? { suggestionId: args.suggestionId } : {}), ...(args.recordId ? { recordId: args.recordId } : {}) }); return inboxApi(ctx, principal, await ctx.db.get(item._id) as Doc<"agentInbox">); } });
