import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

const slot = v.object({ kind: v.union(v.literal("n"), v.literal("s"), v.literal("d"), v.literal("b")), index: v.number() });
const values = v.record(v.string(), v.any());

export default defineSchema({
  users: defineTable({ tokenIdentifier: v.string(), name: v.string(), email: v.optional(v.string()), imageUrl: v.optional(v.string()) }).index("by_token", ["tokenIdentifier"]),
  orgs: defineTable({ name: v.string(), createdBy: v.id("users") }),
  members: defineTable({ orgId: v.id("orgs"), userId: v.id("users"), role: v.union(v.literal("owner"), v.literal("admin"), v.literal("member")) }).index("by_org_user", ["orgId", "userId"]).index("by_user", ["userId"]),
  invites: defineTable({ orgId: v.id("orgs"), token: v.string(), role: v.union(v.literal("admin"), v.literal("member")), createdBy: v.id("users"), expiresAt: v.number(), acceptedBy: v.optional(v.id("users")), acceptedAt: v.optional(v.number()) }).index("by_token", ["token"]).index("by_org", ["orgId"]),
  objects: defineTable({ orgId: v.id("orgs"), key: v.string(), label: v.string(), labelPlural: v.string(), icon: v.optional(v.string()), titleFieldId: v.optional(v.id("fields")), isStandard: v.boolean(), order: v.number() }).index("by_org", ["orgId"]).index("by_org_key", ["orgId", "key"]),
  fields: defineTable({ orgId: v.id("orgs"), objectId: v.id("objects"), key: v.string(), label: v.string(), type: v.union(v.literal("text"), v.literal("number"), v.literal("select"), v.literal("date"), v.literal("boolean"), v.literal("lookup"), v.literal("links")), options: v.optional(v.array(v.object({ id: v.string(), label: v.string(), color: v.optional(v.string()) }))), targetObjectId: v.optional(v.id("objects")), required: v.boolean(), slot: v.optional(slot), encoding: v.number(), retired: v.boolean(), order: v.number() }).index("by_object", ["orgId", "objectId"]).index("by_object_key", ["orgId", "objectId", "key"]),
  records: defineTable({ orgId: v.id("orgs"), objectId: v.id("objects"), values, title: v.string(), ref: v.optional(v.string()), createdBy: v.id("users"), updatedAt: v.number(), n0: v.optional(v.number()), n1: v.optional(v.number()), n2: v.optional(v.number()), n3: v.optional(v.number()), n4: v.optional(v.number()), n5: v.optional(v.number()), n6: v.optional(v.number()), n7: v.optional(v.number()), s0: v.optional(v.string()), s1: v.optional(v.string()), s2: v.optional(v.string()), s3: v.optional(v.string()), s4: v.optional(v.string()), s5: v.optional(v.string()), s6: v.optional(v.string()), s7: v.optional(v.string()), d0: v.optional(v.number()), d1: v.optional(v.number()), d2: v.optional(v.number()), d3: v.optional(v.number()), b0: v.optional(v.boolean()), b1: v.optional(v.boolean()), b2: v.optional(v.boolean()), b3: v.optional(v.boolean()) })
    .index("by_object", ["orgId", "objectId"]).index("by_object_updated", ["orgId", "objectId", "updatedAt"]).index("by_org_ref", ["orgId", "ref"])
    .index("by_n0", ["orgId", "objectId", "n0"]).index("by_n1", ["orgId", "objectId", "n1"]).index("by_n2", ["orgId", "objectId", "n2"]).index("by_n3", ["orgId", "objectId", "n3"]).index("by_n4", ["orgId", "objectId", "n4"]).index("by_n5", ["orgId", "objectId", "n5"]).index("by_n6", ["orgId", "objectId", "n6"]).index("by_n7", ["orgId", "objectId", "n7"])
    .index("by_s0", ["orgId", "objectId", "s0"]).index("by_s1", ["orgId", "objectId", "s1"]).index("by_s2", ["orgId", "objectId", "s2"]).index("by_s3", ["orgId", "objectId", "s3"]).index("by_s4", ["orgId", "objectId", "s4"]).index("by_s5", ["orgId", "objectId", "s5"]).index("by_s6", ["orgId", "objectId", "s6"]).index("by_s7", ["orgId", "objectId", "s7"])
    .index("by_d0", ["orgId", "objectId", "d0"]).index("by_d1", ["orgId", "objectId", "d1"]).index("by_d2", ["orgId", "objectId", "d2"]).index("by_d3", ["orgId", "objectId", "d3"])
    .index("by_b0", ["orgId", "objectId", "b0"]).index("by_b1", ["orgId", "objectId", "b1"]).index("by_b2", ["orgId", "objectId", "b2"]).index("by_b3", ["orgId", "objectId", "b3"]),
  links: defineTable({ orgId: v.id("orgs"), fieldId: v.id("fields"), fromRecordId: v.id("records"), toRecordId: v.id("records") }).index("by_from", ["orgId", "fieldId", "fromRecordId"]).index("by_to", ["orgId", "fieldId", "toRecordId"]).index("by_record_any", ["orgId", "fromRecordId"]).index("by_target_any", ["orgId", "toRecordId"]),
  events: defineTable({ orgId: v.id("orgs"), actor: v.object({ kind: v.union(v.literal("user"), v.literal("agent"), v.literal("automation")), id: v.string() }), action: v.union(v.literal("create"), v.literal("update"), v.literal("delete")), objectId: v.id("objects"), recordId: v.id("records"), before: v.union(values, v.null()), after: v.union(values, v.null()), reason: v.optional(v.string()) }).index("by_record", ["orgId", "recordId"]).index("by_org", ["orgId"]),
});
