import json,hashlib
from pathlib import Path
p=Path('evidence/2026-09-24-unified-build/communications-same-sender-iv')
w=json.loads((p/'C-receipts.json').read_text()); livepath=Path('proofs/communications/evidence/same-sender/live-result.json'); live=json.loads(livepath.read_text()); ledgerpath=Path('proofs/communications/.private/send-ledger.jsonl'); before=ledgerpath.read_bytes(); ledger=[json.loads(x) for x in before.splitlines()]
for m in w['receipts']:
 a=[x for x in live['events'] if x['kind']=='accepted' and x['receipt']['name']==m['sequence']]; assert len(a)==1
 a=a[0]; r=a['receipt']; h=m['headers']
 assert h['from']==a['message']['from']=='shakur@envoylogic.com'; assert h['to']==h['delivered-to']==a['message']['to']=='shakur@codemyvibe.com'; assert h['subject']==a['message']['subject']; assert h['message-id']==r['actualMessageId']; assert 'INBOX' in m['labels']; assert not any(m[k] for k in ['bodyReturned','partsReturned','rawReturned'])
 assert m['threadId']==w['receipts'][0]['threadId']
 if m['sequence']!='Q1': assert h['in-reply-to']==h['references']==w['receipts'][0]['headers']['message-id']==a['message']['inReplyTo']
 rows=[x for x in ledger if x.get('id')==r['reservationId']]; reserves=[x for x in rows if x['kind']=='reservation']; outcomes=[x for x in rows if x['kind']=='outcome']; assert len(reserves)==len(outcomes)==1; s=reserves[0]; assert (s['from'],s['to'],s['contentHash'])==(h['from'],h['to'],r['contentHash']); assert outcomes[0]['status']=='accepted'; assert s['at']<=r['acceptedAt']; m['senderReceipt']=r; m['ledgerReservation']=s; m['ledgerOutcome']=outcomes[0]
assert ledgerpath.read_bytes()==before
w.update(status='PASS exact Q1/Q2/Q3 receipt and ledger linkage',ledgerSha256=hashlib.sha256(before).hexdigest(),ledgerUnchangedByReview=True,liveSnapshotSha256=hashlib.sha256(livepath.read_bytes()).hexdigest(),planSha256=live['planSha256'],claimsLimit='Metadata receipt and local reservation correlation; no body/hash comparison, uniqueness search, latency or full fixture verdict.')
(p/'C-receipts.json').write_text(json.dumps(w,indent=2)+'\n')
style=Path('/Users/urkel/Documents/CodeMyVibe/Business/agent-setup/reference/report-template.html').read_text().split('<style>')[1].split('</style>')[0]
(p/'C-receipts.html').write_text('''<!doctype html><html lang="en"><meta charset="utf-8"><title>Independent C receipt witness</title><style>'''+style+'''</style><body><h1>Independent C receipt witness</h1><p class="meta">c0_verifier · 2026-09-25 UTC · LIVE, read-only</p><div class="decisions"><h2>Bounded PASS</h2><p>All three exact Q messages are in C's INBOX. The complete fixture verdict remains pending root's terminal nine-minute observation. No new sends or allowance are authorized by this check.</p></div><div class="status"><h2>Proven</h2><p>Three fresh Gmail metadata reads on the authorized C account match A→C, exact test subject and each actual sender Message-ID. Q2 and Q3 refer to Q1, and all three share C's mailbox thread. Each receipt matches one prior shared-ledger reservation and one accepted outcome, including exact recipient and content-hash reference. The ledger was unchanged by this read-only comparison.</p></div><h2>Before and after</h2><p>Before: root reported three delivered Q messages. After: c0 independently reread the exact three Gmail IDs and checked sender evidence and ledger linkage. No searches, message bodies, mutations or calendar calls were made. Metadata cannot independently verify the message body's content hash; the hash comparison here correlates the local reservation and sender receipt.</p><p><a href="C-receipts.json">Sanitized independent receipt evidence</a> · <a href="../../../proofs/communications/evidence/same-sender/root-C-receipts.json">Root witness</a> · <a href="review.html">Prior preparation review</a></p><h2>Limits</h2><p>This check proves these three receipts, not mailbox-wide uniqueness, delivery latency, P cutoff duration, production integration or whole-P5 completion. Sender and recipient Gmail IDs and thread IDs are mailbox-specific. The full fixture review awaits the terminal result; no rerun was performed.</p></body></html>''')
print(json.dumps({'status':w['status'],'receipts':len(w['receipts']),'ledgerUnchanged':True,'fullFixture':'PENDING'}))
