import json,hashlib
from pathlib import Path
from datetime import datetime
base=Path('proofs/communications'); out=Path('evidence/2026-09-24-unified-build/communications-same-sender-iv'); sha=lambda b:hashlib.sha256(b).hexdigest(); read=lambda p:json.loads(p.read_text())
mp=base/'evidence/same-sender/source-manifest.json'; manifest=read(mp); assert len(manifest['files'])==34
for path,digest in manifest['files'].items(): assert sha((base/path).read_bytes())==digest,path
aggregate=sha(json.dumps(manifest['files'],sort_keys=True,separators=(',',':')).encode()); assert aggregate==manifest['aggregateSha256']=='c29dfab5c14e841ce38d31d702a54bc6ecea5063a9b3284b892dd7ee45722fa9'; assert sha(mp.read_bytes())=='01a580dc765cf53ade7556b4eec2442f26f248cc7f446de0a902fb1a3ab65db6'
lp=base/'evidence/same-sender/live-result.json'; live=read(lp); run=read(base/'evidence/same-sender/root-execution.json'); result=live['result']; events=live['events']; assert run['exit']==0; assert result['elapsedMs']>=540000; wall=(datetime.fromisoformat(run['endedAt'])-datetime.fromisoformat(run['startedAt'])).total_seconds()*1000; assert wall>=result['elapsedMs']; assert run['sourceAggregate']==aggregate; assert live['planSha256']==run['planSha256']==manifest['planSha256']; assert live['calendarCalls']==result['calendarCalls']==0
ledgerpath=base/'.private/send-ledger.jsonl'; raw=ledgerpath.read_bytes(); rows=[json.loads(x) for x in raw.splitlines()]; reservations=[r for r in rows if r['kind']=='reservation']; prefix='237331e2-1fab-416a-b433-3232acedeab3-'; current=[r for r in reservations if r['id'].startswith(prefix)]; assert len(current)==5; assert sha(raw)==run['ledgerAfterSha256']; prior=b''.join(line for line in raw.splitlines(keepends=True) if prefix.encode() not in line); assert sha(prior)==run['ledgerBeforeSha256']
accepted=[e for e in events if e['kind']=='accepted']; assert [e['message']['name'] for e in accepted]==['P1','Q1','reply-P','Q2','Q3']; assert result['receipts']==[e['receipt'] for e in accepted]
A='shakur@envoylogic.com';B='reply@repliedfor.com';C='shakur@codemyvibe.com'; linked=[]
for e in accepted:
 m=e['message']; r=e['receipt']; assert m['from']!=C; assert (m['from'],m['to']) in [(A,B),(A,C),(B,A)]; s=[s for s in current if s['id']==r['reservationId']]; assert len(s)==1; s=s[0]; assert (s['from'],s['to'],s['contentHash'])==(m['from'],m['to'],r['contentHash']); assert sha(json.dumps(m,separators=(',',':'),ensure_ascii=False).encode())==r['contentHash']; outcomes=[x for x in rows if x['kind']=='outcome' and x['id']==s['id']]; assert len(outcomes)==1 and outcomes[0]['status']=='accepted'; assert s['at']<=r['acceptedAt']<=outcomes[0]['at']; linked.append({'name':m['name'],'from':m['from'],'to':m['to'],'receipt':r,'reservation':s,'outcome':outcomes[0]})
qs=[x for x in result['receipts'] if x['name'].startswith('Q')]; gaps=[qs[i]['acceptedAt']-qs[i-1]['acceptedAt'] for i in [1,2]]; assert all(g>=120000 for g in gaps)
reply=[e for e in events if e['kind']=='reply-matched']; assert len(reply)==1; cutoff=result['cutoff']; assert [c['name'] for c in cutoff]==['P2','P3']; assert all(c['denied'] and c['at']>reply[0]['at'] for c in cutoff); assert not any(r.get('id') in [prefix+'P2',prefix+'P3'] for r in rows); assert len([e for e in events if e['kind']=='P1-received'])==1
end=int(datetime.fromisoformat(run['endedAt']).timestamp()*1000); used={a:sum(r['from']==a and end-86400000<r['at']<=end for r in reservations) for a in [A,B,C]}; assert used=={A:5,B:5,C:0}
for r in current: assert sum(x['from']==r['from'] and r['at']-86400000<x['at']<=r['at'] for x in reservations)<=5
w=read(out/'C-receipts.json'); assert len(w['receipts'])==3; assert w['status'].startswith('PASS'); assert w['ledgerSha256']==sha(raw)
for c in w['receipts']: assert c['senderReceipt']==next(q for q in qs if q['name']==c['sequence'])
assert ledgerpath.read_bytes()==raw
verdict={'verdict':'APPROVE bounded actual-provider same-sender fixture','reviewer':'c0_verifier','operator':'root','sourceFiles':34,'sourceAggregate':aggregate,'manifestSha256':sha(mp.read_bytes()),'planSha256':live['planSha256'],'terminalEvidenceSha256':sha(lp.read_bytes()),'rootExit':0,'observationFromSequenceStartMs':result['elapsedMs'],'rootWallElapsedMs':round(wall,3),'qAcceptanceGapsMs':gaps,'PfollowupCutoff':cutoff,'ledgerPreviousPrefixPreserved':True,'ledgerSha256':sha(raw),'currentReservations':linked,'rolling24hAtTerminal':used,'independentCReceiptReads':3,'reviewProviderWrites':0,'calendarCalls':0,'sourceUnchanged':True,'remaining':['Product integration and two-browser timeline not established','Provider history/watch/reconnect not established','H0 SERVICE uses synthetic identities; no production authorization certification','Metadata receipt checks do not independently compare message-body bytes','Whole P5 remains open'],'evidenceAttribution':'Root executed LIVE sends/P1 and reply receive checks and local H0 SERVICE; c0 independently read exact C metadata and replayed local terminal evidence assertions. No send rerun.'}
(out/'live-verdict.json').write_text(json.dumps(verdict,indent=2)+'\n'); print(json.dumps({k:verdict[k] for k in ['verdict','observationFromSequenceStartMs','qAcceptanceGapsMs','rolling24hAtTerminal','sourceUnchanged']}))
