import assert from 'node:assert/strict';
import {readFileSync, writeFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
const root = new URL('../../../proofs/communications/', import.meta.url);
const local = new URL('./', import.meta.url);
const raw = path => readFileSync(new URL(path, root));
const json = path => JSON.parse(raw(path));
const sha = value => createHash('sha256').update(value).digest('hex');
const before = JSON.parse(readFileSync(new URL('before.json', local)));
const manifest = json('evidence/source-manifest.json');
const finalManifest = 'd245915fed6bcc2420d29f7c4329b0bafb08835432d9e52106180c974065d887';
assert.equal(sha(raw('evidence/source-manifest.json')), finalManifest);
assert.equal(sha(raw('evidence/manifest-before-calendar-count-correction.json')), before.sourceManifest);
const priorManifest = json('evidence/manifest-before-calendar-count-correction.json');
assert.deepEqual(manifest, {...priorManifest, calendarCalls:6, calendarCallsScope:'Root one-event lifecycle only; exact-ID read witnesses are separate evidence'});
for (const [path, expected] of Object.entries(manifest.files)) assert.equal(sha(raw(path)), expected, path);
for (const [path, expected] of Object.entries(before.privateArtifactHashes)) assert.equal(sha(raw('.private/' + path)), expected, 'Private plan/ledger changed: ' + path);
assert.equal(sha(raw('evidence/calendar-read-check.json')), before.calendarReadProvenanceHash);
const rows = raw('.private/send-ledger.jsonl').toString().trim().split('\n').map(JSON.parse);
assert.equal(rows[0].cap, 5);
assert.equal(rows[0].windowMs, 86400000);
const reserved = rows.filter(r => r.kind === 'reservation'), outcomes = rows.filter(r => r.kind === 'outcome');
assert.equal(reserved.length, 5); assert.equal(new Set(reserved.map(r => r.id)).size, 5);
assert.equal(outcomes.length, 5); assert(outcomes.every(r => r.status === 'accepted'));
const plan = json('.private/resume-plan.json'), original = json('.private/live-plan.json');
const acceptedCounts = {};
for (const r of reserved) {
  const message = plan.messages.find(m => r.id === plan.run + '-' + m.name);
  assert(message); assert.equal(r.contentHash, sha(JSON.stringify(message)));
  assert.equal(r.from, message.from); assert.equal(r.to, message.to);
  assert(outcomes.some(o => o.id === r.id && o.at >= r.at));
  acceptedCounts[r.from] = (acceptedCounts[r.from] ?? 0) + 1;
}
assert.deepEqual(acceptedCounts, {'shakur@envoylogic.com':1,'reply@repliedfor.com':4});
const mail = json('evidence/live-resume.json');
assert.equal(mail.status, 'PASS'); assert.equal(mail.receipts.length, 5); assert.equal(mail.observed.length, 5);
assert.equal(new Set(mail.receipts.map(r => r.name)).size, 5); assert.equal(new Set(mail.observed.map(r => r.name)).size, 5);
assert.deepEqual(mail.actualMailAccepted, acceptedCounts); assert.equal(mail.priorSendsRepeated, false);
assert(mail.elapsedMs >= 540000); assert.equal(mail.cutoffChecks.length, 2); assert(mail.cutoffChecks.every(x => x.denied));
const receipt = name => mail.receipts.find(r => r.name === name);
const observed = name => mail.observed.find(r => r.name === name);
const qSpacing = [Date.parse(receipt('Q2').at)-Date.parse(receipt('Q1').at), Date.parse(receipt('Q3').at)-Date.parse(receipt('Q2').at)];
assert(qSpacing.every(ms => ms >= 120000));
assert.equal(observed('reply-P').thread, receipt('P1').thread);
assert.notEqual(observed('Q1').thread, observed('reply-P').thread);
const diagnostic = json('evidence/receipt-diagnostic-gmail.json');
const imap = json('evidence/receipt-diagnostic-imap.json');
assert.equal(diagnostic.providerP1.id, receipt('P1').providerRef);
assert.equal(diagnostic.providerP1.messageId, plan.verifiedP1Reference);
assert.equal(imap.matches.length, 1); assert.equal(imap.matches[0].messageId, plan.verifiedP1Reference);
assert.notEqual(original.messages[0].messageId, plan.verifiedP1Reference);
const cal = json('evidence/calendar-live.json');
const attempts = raw('.private/calendar-attempt.jsonl').toString().trim().split('\n').map(JSON.parse);
assert.deepEqual(attempts.map(r => r.kind), ['create-intent','created','reschedule-intent','rescheduled','delete-intent','deleted']);
assert(attempts.every(r => r.id === cal.eventId));
assert.equal(cal.apiCalls, 6); assert.equal(cal.result.created, 1); assert.equal(cal.result.rescheduled, 1); assert.equal(cal.result.deleted, 1);
assert.equal(cal.result.attendees, 0); assert.equal(cal.result.sendUpdates, 'none');
const witness = JSON.parse(readFileSync(new URL('calendar-get.json', local)));
assert.equal(witness.eventId, cal.eventId); assert.equal(witness.httpStatus, 200); assert.equal(witness.tombstone, true);
const result = {status:'PASS bounded retained evidence plus fresh exact-event read',verifier:'h0_builder',sourceManifest:finalManifest,priorManifest:before.sourceManifest,metadataCorrectionOnly:true,sourceFiles:Object.keys(manifest.files).length,offlineTests:29,ledgerReservations:reserved.length,ledgerAcceptedOutcomes:outcomes.length,acceptedCounts,uniqueObservedMessages:5,qSpacingMs:qSpacing,observationMs:mail.elapsedMs,replyThreadMatchesP:true,unrelatedQThreadDistinct:true,calendarLedgerSteps:attempts.length,calendarProviderCallsInHistoricalRun:cal.apiCalls,freshCalendarGet:witness.httpStatus,calendarCancelled:true,originalSourceAndPrivateLedgersUnchanged:true,originalCalendarWitnessPreserved:true,newMailWrites:0,newCalendarWrites:0,notes:['Retained mail evidence reviewed; no independent redelivery or new mailbox receipt lookup.','Root corrected manifest calendarCalls to6; exact file-map and all other metadata unchanged except explanatory scope.','Whole P5 remains open.']};
writeFileSync(new URL('result.json', local), JSON.stringify(result,null,2)+'\n');
console.log(JSON.stringify(result,null,2));
