import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,readFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {claimJournal} from '../continuation.mjs';
import {boundedRecurringProvider,D,E,RUN} from './sandbox-policy.mjs';
function fixture(){const calls=[],r={clocks:new Map([['clock_F',{id:'clock_F',label:'F',time:1000}],['clock_H',{id:'clock_H',label:'H',time:1000}]]),customers:new Set(['cus_F']),product:'prod_fixture',price:'price_fixture',paymentMethods:new Set(['pm_fixture']),commands:new Map(),subscriptions:new Set(['sub_fixture']),schedules:new Set(['sub_sched_fixture'])};const raw={receipts:[],request:async(...a)=>{calls.push(a);return{id:'synthetic',livemode:false};}};return{r,calls,p:boundedRecurringProvider(raw,{wrap:x=>x},r,1000),raw};}
test('only D has writes, and arbitrary payment or email routes never reach Stripe',async()=>{const{p,calls}=fixture();for(const account of [E,undefined,'acct_other'])await assert.rejects(p.request('POST','/v1/setup_intents',{},account,'bad'));for(const path of ['/v1/invoices/in_1/pay','/v1/payment_intents','/v1/customers/cus_F','/v1/refunds'])await assert.rejects(p.request('POST',path,{},D,path));assert.equal(calls.length,0);});
test('fixture price and setup parameters cannot increase terms or add a recipient',async()=>{const{p,calls}=fixture(),price={product:'prod_fixture',currency:'usd',unit_amount:301,'recurring[interval]':'day','recurring[interval_count]':1,'recurring[usage_type]':'licensed',billing_scheme:'per_unit'};for(const update of [{unit_amount:302},{currency:'eur'},{'recurring[interval]':'month'},{email:'test@invalid'}])await assert.rejects(p.request('POST','/v1/prices',{...price,...update},D,'invalid'));assert.equal(calls.length,0);await p.request('POST','/v1/prices',price,D,'price');assert.equal(calls.length,1);await assert.rejects(p.request('POST','/v1/prices',price,D,'second-price'));assert.equal(calls.length,1);});
test('clock advances require exact ownership, monotonic time, two-interval and per-clock caps',async()=>{const{p,r,calls}=fixture();for(const [id,time]of[['other',1100],['clock_F',1000],['clock_F',173801],['clock_F',1000.5]])await assert.rejects(p.request('POST','/v1/test_helpers/test_clocks/'+id+'/advance',{frozen_time:time},D,'bad'));assert.equal(calls.length,0);for(const label of ['F','H']){for(let n=0;n<(label==='F'?8:6);n++){const c=r.clocks.get('clock_'+label);await p.request('POST','/v1/test_helpers/test_clocks/'+c.id+'/advance',{frozen_time:c.time+60},D,label+n);c.time+=60;}const c=r.clocks.get('clock_'+label);await assert.rejects(p.request('POST','/v1/test_helpers/test_clocks/'+c.id+'/advance',{frozen_time:c.time+60},D,label+'extra'));}assert.equal(calls.length,14);});
test('setup permits exactly four card-only off-session confirmations and refuses duplicate keys',async()=>{const{p,calls}=fixture(),params={customer:'cus_F',usage:'off_session',payment_method:'pm_card_visa','payment_method_types[0]':'card',confirm:true};for(const update of [{customer:'cus_other'},{usage:'on_session'},{payment_method:'pm_unknown'},{receipt_email:'test@invalid'}])await assert.rejects(p.request('POST','/v1/setup_intents',{...params,...update},D,'invalid'));for(let n=0;n<4;n++)await p.request('POST','/v1/setup_intents',params,D,'setup'+n);for(const key of ['setup0','setup5'])await assert.rejects(p.request('POST','/v1/setup_intents',params,D,key));assert.equal(calls.length,4);});
test('only registered exact recurring commands may update a card or cancel without proration',async()=>{const{p,r,calls}=fixture();r.commands.set('recurring:cancel',{kind:'cancel',schedule:'sub_sched_fixture'});r.commands.set('recurring:card',{kind:'card',subscription:'sub_fixture'});await assert.rejects(p.request('POST','/v1/subscription_schedules/sub_sched_other/cancel',{invoice_now:false,prorate:false},D,'recurring:cancel'));await assert.rejects(p.request('POST','/v1/subscription_schedules/sub_sched_fixture/cancel',{invoice_now:true,prorate:false},D,'recurring:cancel'));assert.equal(calls.length,0);await p.request('POST','/v1/subscription_schedules/sub_sched_fixture/cancel',{invoice_now:false,prorate:false},D,'recurring:cancel');await p.request('POST','/v1/subscriptions/sub_fixture',{default_payment_method:'pm_fixture'},D,'recurring:card');assert.equal(calls.length,2);});
test('one-shot claim is durable before provider effects and an unknown response never retries',async()=>{const dir=mkdtempSync(join(tmpdir(),'remold-recurring-journal-')),j=claimJournal(dir,RUN,{synthetic:true}),{r}=fixture();assert.throws(()=>claimJournal(dir,RUN,{}),/EEXIST/);let calls=0;const raw={receipts:[],request:async()=>{calls++;const rows=readFileSync(j.path,'utf8').trim().split('\n').map(JSON.parse);assert.equal(rows.at(-1).kind,'write-attempt');throw Error('simulated unknown response');}};const p=boundedRecurringProvider(raw,j,r,1000),params={customer:'cus_F',usage:'off_session',payment_method:'pm_card_visa','payment_method_types[0]':'card',confirm:true};await assert.rejects(p.request('POST','/v1/setup_intents',params,D,'setup'),/unknown response/);await assert.rejects(p.request('POST','/v1/setup_intents',params,D,'setup'),/Repeated/);assert.equal(calls,1);const rows=readFileSync(j.path,'utf8').trim().split('\n').map(JSON.parse);assert.equal(rows.at(-1).kind,'write-error');assert.equal(rows.at(-1).outcome,'unknown');});
test('finite activations bind approved terms and stop after exactly three schedules',async()=>{const{p,r,calls}=fixture();const params={customer:'cus_F',start_date:1000,end_behavior:'cancel','default_settings[collection_method]':'charge_automatically','default_settings[default_payment_method]':'pm_fixture','default_settings[automatic_tax][enabled]':false,'phases[0][collection_method]':'charge_automatically','phases[0][automatic_tax][enabled]':false,'phases[0][items][0][price]':'price_fixture','phases[0][items][0][quantity]':1,'phases[0][iterations]':3,'phases[0][proration_behavior]':'none','metadata[remold_commitment]':'commitment','metadata[remold_plan]':'hash'};for(let n=0;n<4;n++)r.commands.set('recurring:'+n,{kind:'activate',customer:'cus_F',start:1000,commitment:'commitment',planHash:'hash'});for(const update of [{'phases[0][iterations]':4},{'phases[0][items][0][price]':'price_other'},{'default_settings[automatic_tax][enabled]':true},{'metadata[remold_commitment]':'other'},{'application_fee_percent':1}])await assert.rejects(p.request('POST','/v1/subscription_schedules',{...params,...update},D,'recurring:0'));assert.equal(calls.length,0);for(let n=0;n<3;n++)await p.request('POST','/v1/subscription_schedules',params,D,'recurring:'+n);await assert.rejects(p.request('POST','/v1/subscription_schedules',params,D,'recurring:3'));assert.equal(calls.length,3);});
