import { defineTable } from 'convex/server';
import { v } from 'convex/values';
import { actor } from '../../packages/contracts/authority';
import { externalCapability, payload, state, finalityRule, financialReceipt } from '../../packages/contracts/integrations';

export const integrationTables = {
  safetyTargets: defineTable({ orgId: v.id('orgs'), bindingId: v.id('integrationBindings'), documentRef: v.string(), providerRef: v.string(), kind: v.union(v.literal('payment'), v.literal('clientRecurring')), currency: v.string(), paidMinor: v.number(), refundedMinor: v.number(), pendingRefundMinor: v.number(), anomaly: v.optional(v.string()), pendingCancel: v.optional(v.id('integrationOps')), cancelled: v.boolean(), generation: v.number(), complete: v.boolean(), providerPendingMinor: v.number(), lookupId: v.optional(v.id('integrationLookups')) }).index('by_binding', ['bindingId']).index('by_org', ['orgId']),
  integrationReceipts: defineTable({ orgId: v.id('orgs'), targetId: v.id('safetyTargets'), provider: v.string(), environment: v.string(), account: v.string(), kind: v.union(v.literal('refund'), v.literal('clientRecurringCancel')), receipt: financialReceipt, observedGeneration: v.optional(v.number()), boundOperationId: v.optional(v.id('integrationOps')) }).index('by_receipt', ['provider', 'environment', 'account', 'kind', 'receipt.receiptId']).index('by_target', ['targetId']),
  integrationProviders: defineTable({ provider: v.string(), enabled: v.boolean(), finalityRules: v.array(finalityRule) }).index('by_provider', ['provider']),
  secretReferences: defineTable({ orgId: v.id('orgs'), provider: v.string(), environment: v.string(), account: v.string(), handle: v.string(), version: v.number(), active: v.boolean() }).index('by_org', ['orgId']),
  integrationConnections: defineTable({ orgId: v.id('orgs'), provider: v.string(), environment: v.string(), account: v.string(), secretReferenceId: v.id('secretReferences'), credentialHash: v.string(), connected: v.boolean(), healthy: v.boolean(), version: v.number() }).index('by_credential', ['credentialHash']).index('by_tuple', ['provider', 'environment', 'account']).index('by_org', ['orgId']),
  integrationBindings: defineTable({ orgId: v.id('orgs'), connectionId: v.id('integrationConnections'), provider: v.string(), environment: v.string(), account: v.string(), kind: v.string(), externalId: v.string(), localRecordId: v.optional(v.id('records')), recipient: v.optional(v.string()), connected: v.boolean() }).index('by_tuple', ['provider', 'environment', 'account', 'kind', 'externalId']).index('by_org', ['orgId']),
  integrationIntents: defineTable({ orgId: v.id('orgs'), connectionId: v.id('integrationConnections'), logical: v.string(), kind: v.string(), localRecordId: v.optional(v.id('records')), recipient: v.optional(v.string()), desired: v.union(v.literal('present'), v.literal('deleted')), externalId: v.optional(v.string()), cleanupRequired: v.boolean() }).index('by_logical', ['connectionId', 'logical']),
  integrationCallbacks: defineTable({ orgId: v.id('orgs'), bindingId: v.id('integrationBindings'), eventId: v.string(), digest: v.string(), receivedAt: v.number() }).index('by_event', ['bindingId', 'eventId']),
  integrationObservations: defineTable({ orgId: v.id('orgs'), bindingId: v.id('integrationBindings'), version: v.number(), state: v.string(), observedAt: v.number() }).index('by_binding', ['bindingId']),
  integrationLookups: defineTable({ orgId: v.id('orgs'), connectionId: v.id('integrationConnections'), cursorId: v.id('integrationCursors'), resource: v.string(), traversal: v.string(), pageCount: v.number(), digest: v.string(), completedAt: v.number() }).index('by_traversal', ['cursorId', 'traversal']),
  integrationPages: defineTable({ cursorId: v.id('integrationCursors'), traversal: v.string(), page: v.number(), digest: v.string() }).index('by_page', ['cursorId', 'traversal', 'page']),
  integrationCursors: defineTable({ orgId: v.id('orgs'), connectionId: v.id('integrationConnections'), resource: v.string(), checkpoint: v.number(), traversal: v.string(), nextPage: v.number(), complete: v.boolean() }).index('by_resource', ['connectionId', 'resource']),
  consent: defineTable({ orgId: v.id('orgs'), recipient: v.string(), channel: v.string(), purpose: v.string(), suppressed: v.boolean(), source: v.string(), version: v.number(), at: v.number() }).index('by_recipient', ['orgId', 'recipient', 'channel', 'purpose']),
  usageBudgets: defineTable({ key: v.string(), orgId: v.optional(v.id('orgs')), cap: v.number(), maxConcurrent: v.number(), maxPerRun: v.number(), maxSteps: v.number(), maxRecipients: v.number(), reserved: v.number(), active: v.number(), spent: v.number(), missingUsage: v.boolean(), missingUsageCount: v.number(), anomaly: v.optional(v.string()) }).index('by_key', ['key']),
  integrationOps: defineTable({ orgId: v.id('orgs'), actor, owner: actor, author: actor, adoptedFrom: v.optional(v.id('integrationOps')), actorEpoch: v.number(), actorMembershipId: v.optional(v.id('members')), capability: externalCapability, safety: v.optional(v.object({ targetId: v.id('safetyTargets'), documentRef: v.string(), kind: v.union(v.literal('refund'), v.literal('cancelRecurring')), amountMinor: v.number(), reservationActive: v.boolean(), receiptId: v.optional(v.id('integrationReceipts')), consumedAt: v.optional(v.number()) })), logical: v.string(), bindingId: v.id('integrationBindings'), payload, version: v.number(), approval: v.optional(v.object({ snapshot: payload, version: v.number(), actorEpoch: v.number(), expiresAt: v.number(), approver: v.union(actor, v.object({ grantId: v.id('capabilityGrants') })), approverEpoch: v.optional(v.number()), approverMembershipId: v.optional(v.id('members')) })), grantId: v.optional(v.id('capabilityGrants')), state, reservationUnits: v.number(), reserved: v.number(), usage: v.number(), usageMissing: v.boolean(), step: v.number(), maxSteps: v.number(), fence: v.number(), worker: v.optional(v.string()), leaseUntil: v.number(), permitUntil: v.number(), permitUsed: v.boolean(), attempts: v.number(), cancelRequestedAt: v.optional(v.number()), released: v.boolean(), overrun: v.boolean(), anomaly: v.optional(v.string()), late: v.boolean(), providerRef: v.optional(v.string()), consumedPermits: v.array(v.object({ fence: v.number(), step: v.number() })), receipts: v.array(v.object({ step: v.number(), providerRef: v.string(), usage: v.optional(v.number()), late: v.boolean(), at: v.number() })), absence: v.optional(v.object({ finality: v.union(v.literal('provisional'), v.literal('final')), by: v.string(), at: v.number(), evidence: v.string(), lookupId: v.optional(v.id('integrationLookups')) })) }).index('by_logical', ['orgId', 'actor.id', 'logical']).index('by_org_state', ['orgId', 'state']).index('by_org', ['orgId']).index('by_actor', ['orgId', 'actor.id']),
  integrationEvents: defineTable({ orgId: v.id('orgs'), operationId: v.optional(v.id('integrationOps')), bindingId: v.optional(v.id('integrationBindings')), actor: v.object({ kind: v.union(v.literal('user'), v.literal('agent'), v.literal('adapter'), v.literal('scheduler'), v.literal('operator')), id: v.string() }), name: v.string(), from: v.optional(state), to: v.optional(state), step: v.optional(v.number()), fence: v.optional(v.number()), usageDelta: v.optional(v.number()), usageKnown: v.optional(v.boolean()), amountMinor: v.optional(v.number()), currency: v.optional(v.string()), at: v.number() }).index('by_operation', ['operationId']).index('by_org_at', ['orgId', 'at']),
};
