import assert from 'node:assert/strict';
import {execFileSync} from 'node:child_process';
import {writeFileSync} from 'node:fs';
import {randomUUID} from 'node:crypto';
import {ConvexHttpClient} from 'convex/browser';
import {makeFunctionReference} from 'convex/server';
const client=new ConvexHttpClient('http://127.0.0.1:3500',{logger:false}),call=(n,a)=>client.mutation(makeFunctionReference(n),a),read=(n,a)=>client.query(makeFunctionReference(n),a);
const cli=(n,a)=>JSON.parse(execFileSync(process.execPath,['../../../node_modules/convex/bin/main.js','run',n,JSON.stringify(a)],{encoding:'utf8',stdio:['ignore','pipe','pipe']}));
const wait=ms=>new Promise(r=>setTimeout(r,ms));
const f=cli('harness:seed',{run:randomUUID(),tokens:Array.from({length:10},randomUUID)});
const child=await call('runner:hire',{token:f.A.sessions.owner,name:'IV lost-result descendant',reportsTo:f.A.actors.manager,sessionToken:randomUUID()});
await call('harness:grant',{token:f.A.sessions.owner,target:f.A.actors.manager,capability:'agent.manage',scope:{kind:'agents',agents:[child.id]},mode:'direct',delegate:false,expires:Date.now()+60000});
const grant=await call('harness:grant',{token:f.A.sessions.owner,target:f.A.actors.manager,capability:'model.call',scope:{kind:'model',maxUnitsPerRun:2,maxSteps:1},mode:'direct',delegate:true,expires:Date.now()+60000});
await call('harness:grant',{token:f.A.sessions.manager,target:child.id,parent:grant,capability:'model.call',scope:{kind:'model',maxUnitsPerRun:1,maxSteps:1},mode:'direct',delegate:false,expires:Date.now()+50000});
const task=await call('runner:create',{token:f.A.sessions.owner,assignee:child.id,binding:f.A.binding,title:'IV accepted response lost then manager fired',dependsOn:[],maxAttempts:1,fault:'loseResponse',intervalMs:150,occurrences:3});
await call('runner:start',{token:f.A.sessions.owner,id:task});
let before;for(let i=0;i<80;i++){before=await read('runner:task',{token:f.A.sessions.owner,id:task});if(before.status==='unknown')break;await wait(100)}assert.equal(before.status,'unknown');
const dependent=await call('runner:create',{token:f.A.sessions.owner,assignee:child.id,binding:f.A.binding,title:'IV dependent must stay paused',dependsOn:[task],maxAttempts:1});
await call('runner:start',{token:f.A.sessions.owner,id:dependent});
await call('runner:fire',{token:f.A.sessions.owner,target:f.A.actors.manager});
const after=await read('runner:task',{token:f.A.sessions.owner,id:task});assert.equal(after.status,'paused');
const readOrg=()=>JSON.parse(execFileSync(process.execPath,['../../../node_modules/convex/bin/main.js','data','orgs','--limit','1000','--format','json'],{encoding:'utf8',stdio:['ignore','pipe','pipe']})).find(o=>o._id===f.A.org);
const spentBefore=readOrg().spent;
await call('runner:recover',{token:f.A.sessions.owner,id:task});
let recovered;for(let i=0;i<80;i++){recovered=await read('runner:task',{token:f.A.sessions.owner,id:task});if(recovered.artifact)break;await wait(100)}
assert.ok(recovered.artifact);assert.equal(recovered.status,'paused');assert.equal(recovered.operation,before.operation);assert.equal(recovered.attempts,1);assert.equal(recovered.occurrence,1);assert.equal(recovered.remaining,3);
await Promise.all(Array.from({length:3},()=>call('runner:recover',{token:f.A.sessions.owner,id:task})));
await assert.rejects(call('runner:reassign',{token:f.A.sessions.owner,id:task,assignee:f.A.actors.child}),/resolve old outcome before reassignment/);
await wait(500);
const op=await read('harness:operation',{token:f.A.sessions.owner,id:recovered.operation}),snapshot=cli('runner:inspect',{org:f.A.org}),dep=await read('runner:task',{token:f.A.sessions.owner,id:dependent}),finalTask=await read('runner:task',{token:f.A.sessions.owner,id:task}),spentAfter=readOrg().spent;
assert.equal(op.state,'confirmed');assert.equal(op.receipts.length,1);assert.equal(op.receipts[0].late,true);assert.equal(op.usage,1);assert.equal(snapshot.effects.length,1);assert.equal(spentAfter-spentBefore,1);assert.equal(dep.status,'paused');assert.equal(dep.attempts,0);assert.equal(finalTask.status,'paused');assert.equal(finalTask.occurrence,1);
const output={pass:true,beforeTaskStatus:before.status,afterTaskStatus:finalTask.status,operationState:op.state,providerEffects:snapshot.effects.length,receiptCount:op.receipts.length,late:op.receipts[0].late,usage:op.usage,spentBefore,spentAfter,duplicateRecoverRequests:3,dependentStatus:dep.status,dependentAttempts:dep.attempts,occurrence:finalTask.occurrence,remaining:finalTask.remaining,artifactRecovered:true,reassignmentDenied:true};
writeFileSync('../../../evidence/2026-09-24-unified-build/native-iv/r2/lost-then-fired.json',JSON.stringify(output,null,2)+'\n');console.log(JSON.stringify(output));
