import assert from 'node:assert/strict';
import { readFileSync, writeFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { randomUUID } from 'node:crypto';
import { Client } from '../../../packages/mcp/node_modules/@modelcontextprotocol/sdk/dist/esm/client/index.js';
import { StdioClientTransport } from '../../../packages/mcp/node_modules/@modelcontextprotocol/sdk/dist/esm/client/stdio.js';
import { ConvexHttpClient } from 'convex/browser';
import { makeFunctionReference } from 'convex/server';
const url = readFileSync('.env.local', 'utf8').match(/^CONVEX_URL=(.+)$/m)?.[1];
assert.equal(url, 'http://127.0.0.1:3500');
const client = new ConvexHttpClient(url, { logger: false });
const call = (name, args) => client.mutation(makeFunctionReference(name), args);
const read = (name, args) => client.query(makeFunctionReference(name), args);
const cli = (name, args) => JSON.parse(execFileSync(process.execPath, ['../../../node_modules/convex/bin/main.js', 'run', name, JSON.stringify(args)], { encoding: 'utf8' }));
const results = [];
const wait = ms => new Promise(resolve => setTimeout(resolve, ms));
async function until(token, id, status, waiting = []) {
  for (let i = 0; i < 80; i++) {
    const task = await read('runner:task', { token, id });
    if (task.status === status) return task;
    if (['paused', 'failed', 'unknown'].includes(task.status) && !waiting.includes(task.status)) throw Error(`Unexpected ${task.status}, wanted ${status}`);
    await wait(100);
  }
  throw Error(`Task did not reach ${status}`);
}
try {
  const f = cli('harness:seed', { run: randomUUID(), tokens: Array.from({ length: 10 }, () => randomUUID()) });
  const task = await call('runner:create', { token: f.A.sessions.owner, assignee: f.A.actors.child, binding: f.A.binding, title: 'Synthetic assigned work', dependsOn: [], maxAttempts: 2 });
  await assert.rejects(read('runner:task', { token: f.B.sessions.owner, id: task }), /tenant denied/);
  assert.equal((await read('runner:task', { token: f.A.sessions.owner, id: task })).status, 'ready');
  results.push({ name: 'Owner assigns work; foreign tenant cannot read known task ID', pass: true });
  const common = { token: f.A.sessions.owner, assignee: f.A.actors.child, binding: f.A.binding, dependsOn: [], maxAttempts: 2 };
  await call('harness:grant', { token: f.A.sessions.owner, target: f.A.actors.child, capability: 'model.call', scope: { kind: 'model', maxUnitsPerRun: 2, maxSteps: 1 }, mode: 'direct', delegate: false, expires: Date.now() + 60000 });
  const bridge = new Client({ name: 'native-proof-external-client', version: '1' });
  const transport = new StdioClientTransport({ command: process.execPath, args: ['mcp.mjs'], cwd: process.cwd(), env: { PATH: process.env.PATH, REMOLD_PROOF_TOKEN: f.A.sessions.child }, stderr: 'pipe' });
  try {
    await bridge.connect(transport);
    assert.deepEqual((await bridge.listTools()).tools.map(t => t.name).sort(), ['read_task', 'start_task']);
    const visible = await bridge.callTool({ name: 'read_task', arguments: { id: task } });
    assert.equal(visible.isError, undefined);
    assert.equal(JSON.parse(visible.content[0].text)._id, task);
    const other = await call('runner:create', { ...common, assignee: f.A.actors.manager, title: 'Another assignee' });
    assert.equal((await bridge.callTool({ name: 'read_task', arguments: { id: other } })).isError, true);
    const foreign = await call('runner:create', { token: f.B.sessions.owner, assignee: f.B.actors.child, binding: f.B.binding, title: 'Other workspace', dependsOn: [], maxAttempts: 1 });
    assert.equal((await bridge.callTool({ name: 'read_task', arguments: { id: foreign } })).isError, true);
    assert.equal((await bridge.callTool({ name: 'start_task', arguments: { id: task } })).isError, undefined);
    await until(f.A.sessions.owner, task, 'done');
    results.push({ name: 'External MCP client reads and starts assigned work; other assigned and foreign tasks remain unavailable', pass: true });
  } finally { await bridge.close(); }
  const retry = await call('runner:create', { ...common, title: 'First attempt fails, second succeeds', fault: 'retryOnce' });
  const dependent = await call('runner:create', { ...common, title: 'Wait for successful dependency', dependsOn: [retry] });
  await call('runner:start', { token: f.A.sessions.owner, id: dependent });
  assert.equal((await read('runner:task', { token: f.A.sessions.owner, id: dependent })).status, 'blocked');
  await call('runner:start', { token: f.A.sessions.owner, id: retry });
  const retried = await until(f.A.sessions.owner, retry, 'done');
  assert.equal(retried.attempts, 2);
  const completedDependency = await until(f.A.sessions.owner, dependent, 'done');
  let snapshot = cli('runner:inspect', { org: f.A.org });
  assert.equal(snapshot.effects.filter(e => e.operation === retried.operation).length, 1);
  assert.ok(completedDependency.artifact);
  results.push({ name: 'Scheduled retry preserves one effect; dependent work waits and returns attributed artifact', pass: true });
  const recurring = await call('runner:create', { ...common, title: 'Three bounded occurrences', intervalMs: 150, occurrences: 3 });
  await call('runner:start', { token: f.A.sessions.owner, id: recurring });
  const recurred = await until(f.A.sessions.owner, recurring, 'done');
  assert.equal(recurred.occurrence, 3);
  snapshot = cli('runner:inspect', { org: f.A.org });
  assert.equal(snapshot.effects.length, 6);
  results.push({ name: 'Three scheduled recurrence occurrences each produce one logical effect', pass: true });
  const unknown = await call('runner:create', { ...common, title: 'Accepted result is lost', fault: 'loseResponse' });
  await call('runner:start', { token: f.A.sessions.owner, id: unknown });
  await until(f.A.sessions.owner, unknown, 'unknown');
  await wait(400);
  const unknownState = await read('runner:task', { token: f.A.sessions.owner, id: unknown });
  assert.equal(unknownState.attempts, 1);
  snapshot = cli('runner:inspect', { org: f.A.org });
  assert.equal(snapshot.effects.filter(e => e.operation === unknownState.operation).length, 1);
  results.push({ name: 'Lost accepted response stays unknown and does not blindly retry', pass: true });
  const afterUnknown = await call('runner:create', { ...common, title: 'Wait for recovered provider outcome', dependsOn: [unknown] });
  await call('runner:start', { token: f.A.sessions.owner, id: afterUnknown });
  await call('runner:recover', { token: f.A.sessions.owner, id: unknown });
  const recovered = await until(f.A.sessions.owner, unknown, 'done', ['unknown']);
  assert.equal(recovered.attempts, 1);
  assert.equal(recovered.operation, unknownState.operation);
  assert.ok(recovered.artifact);
  await until(f.A.sessions.owner, afterUnknown, 'done');
  await call('runner:recover', { token: f.A.sessions.owner, id: unknown });
  snapshot = cli('runner:inspect', { org: f.A.org });
  assert.equal(snapshot.effects.filter(e => e.operation === recovered.operation).length, 1);
  results.push({ name: 'Provider lookup resolves an unknown result without a new execution or duplicate effect', pass: true });
  const hired = await call('runner:hire', { token: f.A.sessions.owner, name: 'Synthetic replacement worker', reportsTo: f.A.actors.manager, sessionToken: randomUUID() });
  await assert.rejects(call('runner:hire', { token: f.B.sessions.owner, name: 'Cross tenant hire', reportsTo: f.A.actors.manager, sessionToken: randomUUID() }), /tenant denied/);
  assert.equal(hired.reportsTo, f.A.actors.manager);
  results.push({ name: 'Human hires a default-unprivileged worker with tenant-bound reporting line', pass: true });
  const queued = await call('runner:create', { ...common, assignee: hired.id, title: 'Paused on manager firing' });
  await call('runner:fire', { token: f.A.sessions.owner, target: f.A.actors.manager });
  assert.equal((await read('runner:task', { token: f.A.sessions.owner, id: queued })).status, 'paused');
  await assert.rejects(call('harness:propose', { token: f.A.sessions.manager, logical: 'after-fire', binding: f.A.binding, capability: 'model.call', payload: { content: 'forbidden', audience: [], audienceVersion: 1, destination: 'A', schedule: 0, amountMinor: 0, currency: 'USD', workflowVersion: 1 }, reservationUnits: 1, maxSteps: 1 }), /actor inactive/);
  await call('runner:reassign', { token: f.A.sessions.owner, id: queued, assignee: f.A.actors.child });
  assert.equal((await read('runner:task', { token: f.A.sessions.owner, id: queued })).generation, 3);
  await call('runner:start', { token: f.A.sessions.owner, id: queued });
  const reassigned = await until(f.A.sessions.owner, queued, 'done');
  assert.equal(reassigned.assignee, f.A.actors.child);
  assert.ok(reassigned.operation);
  assert.ok(reassigned.artifact);
  results.push({ name: 'Manager firing pauses descendant work; explicit reassignment executes under the new owner and generation', pass: true });
  const chained = cli('harness:seed', { run: randomUUID(), tokens: Array.from({ length: 10 }, () => randomUUID()) });
  const delegatedToken = randomUUID();
  const delegatedWorker = await call('runner:hire', { token: chained.A.sessions.owner, name: 'Delegated descendant', reportsTo: chained.A.actors.manager, sessionToken: delegatedToken });
  chained.A.actors.child = delegatedWorker.id;
  chained.A.sessions.child = delegatedToken;
  const expiry = Date.now() + 60000;
  await call('harness:grant', { token: chained.A.sessions.owner, target: chained.A.actors.manager, capability: 'agent.manage', scope: { kind: 'agents', agents: [chained.A.actors.child] }, mode: 'direct', delegate: false, expires: expiry });
  const managerGrant = await call('harness:grant', { token: chained.A.sessions.owner, target: chained.A.actors.manager, capability: 'model.call', scope: { kind: 'model', maxUnitsPerRun: 2, maxSteps: 1 }, mode: 'direct', delegate: true, expires: expiry });
  await call('harness:grant', { token: chained.A.sessions.manager, target: chained.A.actors.child, parent: managerGrant, capability: 'model.call', scope: { kind: 'model', maxUnitsPerRun: 1, maxSteps: 1 }, mode: 'direct', delegate: false, expires: expiry });
  const chainArgs = { token: chained.A.sessions.owner, assignee: chained.A.actors.child, binding: chained.A.binding, dependsOn: [], maxAttempts: 1 };
  const granted = await call('runner:create', { ...chainArgs, title: 'Execute delegated authority' });
  await call('runner:start', { token: chained.A.sessions.child, id: granted });
  await until(chained.A.sessions.owner, granted, 'done');
  const firedUnknown = await call('runner:create', { ...chainArgs, title: 'Lost result before manager firing', fault: 'loseResponse' });
  await call('runner:start', { token: chained.A.sessions.owner, id: firedUnknown });
  const lostBeforeFire = await until(chained.A.sessions.owner, firedUnknown, 'unknown');
  const lostDependent = await call('runner:create', { ...chainArgs, title: 'Stay paused after late receipt', dependsOn: [firedUnknown] });
  await call('runner:start', { token: chained.A.sessions.owner, id: lostDependent });
  const held = await call('runner:create', { ...chainArgs, title: 'Active work before final permit', fault: 'holdBeforePermit' });
  const queuedOne = await call('runner:create', { ...chainArgs, title: 'Queued job one', dependsOn: [held] });
  const queuedTwo = await call('runner:create', { ...chainArgs, title: 'Queued job two', dependsOn: [held] });
  for (const id of [held, queuedOne, queuedTwo]) await call('runner:start', { token: chained.A.sessions.owner, id });
  for (let n = 0; n < 100; n++) {
    if ((await read('runner:task', { token: chained.A.sessions.owner, id: held })).heldBeforePermit) break;
    await wait(50);
  }
  const beforeFire = await read('runner:task', { token: chained.A.sessions.owner, id: held });
  assert.equal(beforeFire.status, 'running');
  assert.equal(beforeFire.heldBeforePermit, true);
  await call('runner:fire', { token: chained.A.sessions.owner, target: chained.A.actors.manager });
  cli('runner:releaseHold', { id: held });
  await wait(350);
  for (const id of [held, queuedOne, queuedTwo]) assert.equal((await read('runner:task', { token: chained.A.sessions.owner, id })).status, 'paused');
  const afterFire = cli('runner:inspect', { org: chained.A.org });
  assert.equal(afterFire.effects.length, 2);
  await assert.rejects(call('runner:recover', { token: chained.A.sessions.owner, id: held }), /unknown outcome required/);
  results.push({ name: 'Delegated task executes; manager firing stops one active and two queued descendant tasks before any further effect', pass: true });
  await call('runner:recover', { token: chained.A.sessions.owner, id: firedUnknown });
  let recoveredPaused;
  for (let n = 0; n < 80; n++) {
    recoveredPaused = await read('runner:task', { token: chained.A.sessions.owner, id: firedUnknown });
    if (recoveredPaused.artifact) break;
    await wait(100);
  }
  assert.ok(recoveredPaused.artifact, 'Late accepted receipt remains recoverable after manager firing');
  assert.equal(recoveredPaused.status, 'paused');
  assert.equal(recoveredPaused.operation, lostBeforeFire.operation);
  assert.equal(recoveredPaused.attempts, 1);
  assert.equal((await read('runner:task', { token: chained.A.sessions.owner, id: lostDependent })).status, 'paused');
  await call('runner:recover', { token: chained.A.sessions.owner, id: firedUnknown });
  await assert.rejects(call('runner:reassign', { token: chained.A.sessions.owner, id: firedUnknown, assignee: chained.A.actors.child }), /resolve old outcome before reassignment/);
  await wait(200);
  assert.equal(cli('runner:inspect', { org: chained.A.org }).effects.length, 2);
  results.push({ name: 'Late accepted result remains recoverable after manager firing while tasks stay paused and completed effects cannot be repeated', pass: true });
  writeFileSync('evidence/native-results.json', JSON.stringify({ results }, null, 2));
  writeFileSync('evidence/.run-result.json', JSON.stringify({ code: 0 }));
} catch (error) {
  console.error(error.message);
  writeFileSync('evidence/native-results.json', JSON.stringify({ results, error: error.message }, null, 2));
  writeFileSync('evidence/.run-result.json', JSON.stringify({ code: 1 }));
  process.exitCode = 1;
}
