import type { Id } from "../_generated/dataModel";
import type { MutationCtx } from "../_generated/server";
import { allocateSlot, kindFor } from "./slots";
import { CURRENCIES } from "./bookingTime";

type FieldDef = { key: string; label: string; type: "text" | "number" | "select" | "date" | "boolean" | "lookup" | "links"; required?: boolean; indexed?: false; target?: string; withTime?: true; protectedFromAgents?: true; options?: { id: string; label: string }[] };
type ObjectDef = { key: string; label: string; plural: string; fields: FieldDef[] };
// Only fields people sort or filter by get an indexed slot; an object has 8
// text slots and notes or address lines would use them up.
const standard: ObjectDef[] = [
  { key: "company", label: "Company", plural: "Companies", fields: [{ key: "name", label: "Name", type: "text", required: true }, { key: "domain", label: "Domain", type: "text" }, { key: "city", label: "City", type: "text" }, { key: "notes", label: "Notes", type: "text", indexed: false }, { key: "street", label: "Street", type: "text", indexed: false }, { key: "state", label: "State", type: "text", indexed: false }, { key: "postalCode", label: "Postal Code", type: "text", indexed: false }, { key: "country", label: "Country", type: "text", indexed: false }] },
  { key: "person", label: "Person", plural: "People", fields: [{ key: "name", label: "Name", type: "text", required: true }, { key: "email", label: "Email", type: "text" }, { key: "phone", label: "Phone", type: "text" }, { key: "title", label: "Title", type: "text" }, { key: "company", label: "Company", type: "lookup", target: "company" }, { key: "linkedin", label: "LinkedIn", type: "text", indexed: false }] },
  { key: "opportunity", label: "Opportunity", plural: "Opportunities", fields: [{ key: "name", label: "Name", type: "text", required: true }, { key: "amount", label: "Amount", type: "number" }, { key: "stage", label: "Stage", type: "select", options: ["new", "contacted", "qualified", "proposal", "won", "lost"].map((id) => ({ id, label: id[0].toUpperCase() + id.slice(1) })) }, { key: "closeDate", label: "Close Date", type: "date" }, { key: "company", label: "Company", type: "lookup", target: "company" }, { key: "person", label: "Person", type: "lookup", target: "person" }, { key: "campaign", label: "Campaign", type: "lookup", target: "campaign" }] },
  { key: "project", label: "Project", plural: "Projects", fields: [{ key: "name", label: "Name", type: "text", required: true }, { key: "status", label: "Status", type: "select", options: ["active", "paused", "done"].map((id) => ({ id, label: id[0].toUpperCase() + id.slice(1) })) }, { key: "company", label: "Company", type: "lookup", target: "company" }] },
  { key: "task", label: "Task", plural: "Tasks", fields: [{ key: "title", label: "Title", type: "text", required: true }, { key: "dueDate", label: "Due Date", type: "date", withTime: true }, { key: "done", label: "Done", type: "boolean" }, { key: "project", label: "Project", type: "lookup", target: "project" }, { key: "blockedBy", label: "Blocked By", type: "links", target: "task" }, { key: "about", label: "About", type: "lookup" }] },
  { key: "note", label: "Note", plural: "Notes", fields: [{ key: "body", label: "Body", type: "text", required: true }, { key: "about", label: "About", type: "lookup" }] },
  { key: "activity", label: "Activity", plural: "Activities", fields: [{ key: "title", label: "Title", type: "text", required: true }, { key: "type", label: "Type", type: "select", options: ["call", "email", "meeting", "payment", "message", "other"].map((id) => ({ id, label: id[0]!.toUpperCase() + id.slice(1) })) }, { key: "when", label: "When", type: "date", withTime: true }, { key: "about", label: "About", type: "lookup" }, { key: "source", label: "Source", type: "text" }] },
  { key: "campaign", label: "Campaign", plural: "Campaigns", fields: [{ key: "name", label: "Name", type: "text", required: true }, { key: "status", label: "Status", type: "select", options: ["planned", "active", "paused", "done"].map((id) => ({ id, label: id[0]!.toUpperCase() + id.slice(1) })) }, { key: "channel", label: "Channel", type: "select", options: [{ id: "email", label: "Email" }, { id: "phone", label: "Phone" }, { id: "inPerson", label: "In person" }, { id: "social", label: "Social" }] }, { key: "startDate", label: "Start Date", type: "date" }, { key: "goal", label: "Goal", type: "text" }, { key: "people", label: "People", type: "links", target: "person" }, { key: "companies", label: "Companies", type: "links", target: "company" }] },
  // Tracking only: Remold records invoices and never charges. Agents may not mark one paid.
  { key: "invoice", label: "Invoice", plural: "Invoices", fields: [{ key: "number", label: "Number", type: "text", required: true }, { key: "company", label: "Company", type: "lookup", target: "company" }, { key: "amount", label: "Amount", type: "number" }, { key: "sent", label: "Sent", type: "date" }, { key: "due", label: "Due", type: "date" }, { key: "paidOn", label: "Paid On", type: "date", protectedFromAgents: true }, { key: "monthly", label: "Monthly", type: "boolean" }, { key: "document", label: "Document", type: "text", indexed: false }] },
  { key: "post", label: "Post", plural: "Posts", fields: [{ key: "title", label: "Title", type: "text", required: true }, { key: "channel", label: "Channel", type: "select", options: [{ id: "tiktok", label: "TikTok" }, { id: "instagram", label: "Instagram" }, { id: "facebook", label: "Facebook" }, { id: "x", label: "X" }, { id: "linkedin", label: "LinkedIn" }, { id: "youtube", label: "YouTube" }, { id: "other", label: "Other" }] }, { key: "planned", label: "Planned", type: "date", withTime: true }, { key: "status", label: "Status", type: "select", options: ["idea", "drafted", "approved", "published", "skipped"].map((id) => ({ id, label: id[0]!.toUpperCase() + id.slice(1) })) }, { key: "text", label: "Text", type: "text", indexed: false }, { key: "mediaLink", label: "Media Link", type: "text", indexed: false }, { key: "publishedLink", label: "Published Link", type: "text", indexed: false }, { key: "campaign", label: "Campaign", type: "lookup", target: "campaign" }] },
  // A campaign's email steps. Agents draft them; only a person approves one, and Remold sends it (convex/campaignSend.ts).
  { key: "email", label: "Email", plural: "Emails", fields: [{ key: "subject", label: "Subject", type: "text", required: true }, { key: "body", label: "Body", type: "text", indexed: false }, { key: "campaign", label: "Campaign", type: "lookup", target: "campaign" }, { key: "followsUp", label: "Follows Up", type: "lookup", target: "email" }, { key: "waitDays", label: "Wait Days", type: "number" }, { key: "sendTo", label: "Send To", type: "select", indexed: false, options: [{ id: "everyone", label: "Everyone" }, { id: "notOpened", label: "Not opened" }, { id: "notClicked", label: "Not clicked" }, { id: "notReplied", label: "Not replied" }] }, { key: "sendAt", label: "Send At", type: "date", withTime: true }, { key: "status", label: "Status", type: "select", options: ["draft", "approved", "sending", "sent", "stopped"].map((id) => ({ id, label: id[0]!.toUpperCase() + id.slice(1) })) }] },
  // A public page people book a time on (convex/bookings.ts). Agents draft pages; only a person turns one live.
  { key: "bookingPage", label: "Booking page", plural: "Booking pages", fields: [{ key: "name", label: "Name", type: "text", required: true }, { key: "description", label: "Description", type: "text", indexed: false }, { key: "minutes", label: "Minutes", type: "number" }, { key: "hours", label: "Hours", type: "text" }, { key: "timezone", label: "Timezone", type: "text" }, { key: "noticeHours", label: "Notice Hours", type: "number" }, { key: "daysAhead", label: "Days Ahead", type: "number" }, { key: "price", label: "Price", type: "number" }, { key: "currency", label: "Currency", type: "select", indexed: false, options: CURRENCIES.map((id) => ({ id, label: id.toUpperCase() })) }, { key: "paymentLink", label: "Payment Link", type: "text", indexed: false }, { key: "campaign", label: "Campaign", type: "lookup", target: "campaign" }, { key: "live", label: "Live", type: "boolean" }] },
];

// Idempotent: objects that already exist in the org are left alone, so a
// newer standard object can be added to an older org.
export async function seedStandard(ctx: MutationCtx, orgId: Id<"orgs">) {
  const ids: Record<string, Id<"objects">> = {};
  const existing = await ctx.db.query("objects").withIndex("by_org", (q) => q.eq("orgId", orgId)).collect();
  for (const object of existing) ids[object.key] = object._id;
  const missing = standard.filter((definition) => !ids[definition.key]);
  for (const definition of missing) ids[definition.key] = await ctx.db.insert("objects", { orgId, key: definition.key, label: definition.label, labelPlural: definition.plural, isStandard: true, order: existing.length + missing.indexOf(definition) });
  for (const definition of standard) {
    const objectId = ids[definition.key]!;
    const present = new Map((await ctx.db.query("fields").withIndex("by_object", (q) => q.eq("orgId", orgId).eq("objectId", objectId)).collect()).map((field) => [field.key, field]));
    for (const [order, field] of definition.fields.entries()) {
      const existing = present.get(field.key);
      // Older orgs gain time of day on standard dates; an explicit false is left alone.
      if (existing) { if (field.withTime && existing.type === "date" && existing.withTime === undefined) await ctx.db.patch(existing._id, { withTime: true }); continue; }
      const kind = field.indexed === false ? undefined : kindFor(field.type);
      const fieldId = await ctx.db.insert("fields", { orgId, objectId, key: field.key, label: field.label, type: field.type, options: field.options, targetObjectId: field.target ? ids[field.target] : undefined, required: field.required ?? false, ...(field.withTime ? { withTime: true } : {}), ...(field.protectedFromAgents ? { protectedFromAgents: true } : {}), slot: kind ? await allocateSlot(ctx, orgId, objectId, kind) : undefined, encoding: 1, retired: false, order });
      if (order === 0) await ctx.db.patch(objectId, { titleFieldId: fieldId });
    }
  }
}

export { standard };
