import { defineSchema, defineTable } from 'convex/server';
import { v } from 'convex/values';
import h0 from './h0_schema';
export default defineSchema({ ...h0.tables,
    adjustmentReceipts:defineTable({binding:v.id('bindings'),document:v.id('documents'),kind:v.union(v.literal('refund'),v.literal('credit'),v.literal('payment')),providerRef:v.optional(v.string()),receiptId:v.optional(v.string()),amountMinor:v.number(),voided:v.optional(v.boolean()),provider:v.optional(v.string()),environment:v.optional(v.string()),account:v.optional(v.string()),sourceRef:v.optional(v.string()),operationId:v.optional(v.string()),status:v.optional(v.union(v.literal('pending'),v.literal('succeeded'),v.literal('failed'),v.literal('cancelled')))}).index('receipt',['provider','environment','account','kind','receiptId']).index('document',['document','kind']).index('source',['provider','environment','account','kind','sourceRef']),
    collections:defineTable({org:v.id('orgs'),binding:v.id('bindings'),document:v.id('documents'),operation:v.id('operations'),amountMinor:v.number(),providerRef:v.optional(v.string())}).index('operation',['operation']).index('document',['document']).index('receipt',['binding','providerRef']),
    lifecycleOps: defineTable({org:v.id('orgs'),actor:v.id('actors'),actorEpoch:v.number(),session:v.id('sessions'),document:v.id('documents'),binding:v.id('bindings'),account:v.string(),action:v.union(v.literal('credit'),v.literal('void')),amountMinor:v.number(),state:v.union(v.literal('prepared'),v.literal('sent'),v.literal('settled')),expires:v.number(),providerRef:v.optional(v.string())}).index('document',['document','state']).index('receipt',['binding','providerRef']),
    payCustomers: defineTable({ org: v.id('orgs'), binding: v.id('bindings'), externalId: v.string(), name: v.string(), deleted: v.boolean() }).index('external', ['binding', 'externalId']),
    quotes: defineTable({ org: v.id('orgs'), binding: v.id('bindings'), customer: v.id('payCustomers'), customerName: v.string(), version: v.number(), amountMinor: v.number(), currency: v.string(), state: v.union(v.literal('draft'), v.literal('accepted')), tokenHash: v.optional(v.string()), expires: v.optional(v.number()), acceptedAt: v.optional(v.number()), deposit: v.optional(v.id('documents')), balance: v.optional(v.id('documents')), attemptMinute: v.optional(v.number()), attemptCount: v.optional(v.number()) }),
    documents: defineTable({ org: v.id('orgs'), binding: v.id('bindings'), customer: v.id('payCustomers'), customerName: v.string(), quote: v.optional(v.id('quotes')), quoteVersion: v.optional(v.number()), kind: v.union(v.literal('deposit'), v.literal('balance'), v.literal('invoice'), v.literal('recurring')), amountMinor: v.number(), currency: v.string(), depositAllocation: v.optional(v.id('documents')), allocatedTo: v.optional(v.id('documents')), state: v.string(), externalId: v.optional(v.string()), paidMinor: v.number(), refundedMinor: v.number(), paymentTokenHash: v.optional(v.string()), paymentTokenExpires: v.optional(v.number()), paymentUrl: v.optional(v.string()), creditedMinor: v.optional(v.number()), adjustmentsComplete: v.optional(v.boolean()), adjustmentEpoch: v.optional(v.number()), charge: v.optional(v.string()), refundBaselineMinor: v.optional(v.number()), creditBaselineMinor: v.optional(v.number()), subscriptionStatus: v.optional(v.string()), disputeAmountMinor: v.optional(v.number()), disputeStatus: v.optional(v.string()), paymentIntent: v.optional(v.string()), subscription: v.optional(v.string()), snapshotHash: v.string(), retentionUntil: v.number() }).index('external', ['binding', 'externalId']).index('paymentToken', ['paymentTokenHash']),
    payCallbacks: defineTable({ binding: v.id('bindings'), eventId: v.string(), digest: v.string(), document: v.id('documents') }).index('event', ['binding', 'eventId']),
    financeMembers: defineTable({ actor: v.id('actors'), role: v.union(v.literal('admin'), v.literal('finance'), v.literal('viewer'), v.literal('removed')) }).index('actor', ['actor']),
    safetyOps: defineTable({ org: v.id('orgs'), actor: v.id('actors'), actorEpoch: v.number(), session: v.id('sessions'), document: v.id('documents'), binding: v.id('bindings'), account: v.string(), action: v.union(v.literal('refund'), v.literal('cancel')), amountMinor: v.number(), logical: v.string(), expires: v.number(), state: v.union(v.literal('prepared'), v.literal('sent'), v.literal('settled')), providerRef: v.optional(v.string()), baselineRefunded: v.number(), providerStatus:v.optional(v.string()), late: v.boolean() }).index('logical', ['org', 'logical']).index('document', ['document', 'state']).index('receipt', ['binding', 'providerRef']),
    payIncoming: defineTable({ binding: v.id('bindings'), eventId: v.string(), type: v.string(), externalId: v.string(), digest: v.string(), done: v.boolean() }).index('event', ['binding', 'eventId']).index('pending', ['binding', 'done']),
});
