#!/usr/bin/env node
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { z } from "zod";
import { RemoldClient, RemoldError } from "./client.js";

declare const process: { env: Record<string, string | undefined>; exit(code: number): never; };
const url = process.env.REMOLD_URL, key = process.env.REMOLD_KEY;
if (!url || !key) { console.error("REMOLD_URL and REMOLD_KEY are required"); process.exit(1); }
const client = new RemoldClient({ url, key });
const server = new McpServer({ name: "remold", version: "0.0.0" }, { instructions: "Remold is the team's CRM, and it is meant to be reshaped to fit how the team works. Records are named by a three-word code like brisk-ember-oyster; use codes or ids when you refer to one. Start with remold_inbox: pending items are work left for you. Prefer remold_propose_change; a person applies it. remold_apply_change only works for actions the team granted you. When the work needs a field, object or select option that does not exist, check remold_objects, then propose it with remold_propose_shape and say why. Propose retiring, archiving or reordering what no longer fits the same way. Once remold_shape_proposals shows it applied, use it. Email campaigns: create a campaign record (channel email), link people in its people field (CSV import adds many), then draft email records (subject, body, campaign, status draft; merge tags {{firstName|there}}, {{name}}, {{company}}) and follow-ups (followsUp the earlier email, waitDays, sendTo notOpened, notClicked or notReplied). Check them with remold_email_preview. You cannot approve an email or start a campaign: ask a person to approve each email on the campaign page and press Start campaign. You may stop an email. Later, read remold_campaign_report, use remold_mark_replied for replies you learn of elsewhere, and draft follow-ups for people who did not reply." });
const result = async (run: () => Promise<unknown>) => { try { return { content: [{ type: "text" as const, text: JSON.stringify(await run(), null, 2) }] }; } catch (error) { const item = error instanceof RemoldError ? error : new RemoldError("Something went wrong", "INTERNAL"); return { isError: true, content: [{ type: "text" as const, text: `${item.code}: ${item.message}` }] }; } };
server.registerTool("remold_me", { description: "Show the CRM organisation, this agent's grants, and pending work counts.", inputSchema: {} }, () => result(() => client.me()));
server.registerTool("remold_objects", { description: "List CRM objects in navigation order with their fields in order, retired fields, title field, and slotsLeft: how many more indexed (searchable and sortable) fields of each kind the object can take. Select and lookup fields use text slots. Archived objects are left out unless includeArchived.", inputSchema: { includeArchived: z.boolean().optional() } }, (args) => result(() => client.objects(args)));
server.registerTool("remold_list_records", { description: "List records for one object. Narrow with filters (all must match, e.g. people where company is Atlas) and one date or number range. Sort, filter and range fields must be indexed.", inputSchema: { object: z.string(), cursor: z.string().optional(), limit: z.number().int().optional(), sort: z.object({ field: z.string(), direction: z.enum(["asc", "desc"]) }).optional(), filter: z.object({ field: z.string(), value: z.string() }).optional().describe("one filter; same as a single entry in filters"), filters: z.array(z.object({ field: z.string(), value: z.string() })).optional(), range: z.object({ field: z.string(), from: z.string().optional(), to: z.string().optional() }).optional().describe("from and to are YYYY-MM-DD or ISO times; either may be left out") } }, (args) => result(() => client.listRecords(args)));
server.registerTool("remold_get_record", { description: "Get one record and its recent audit events by record id or three-word code.", inputSchema: { idOrRef: z.string() } }, (args) => result(() => client.getRecord(args.idOrRef)));
server.registerTool("remold_search", { description: "Search record titles, optionally within one object.", inputSchema: { q: z.string(), object: z.string().optional(), limit: z.number().int().optional() } }, (args) => result(() => client.search(args)));
server.registerTool("remold_related", { description: "Find records related to a record through objectKey.fieldKey.", inputSchema: { idOrRef: z.string(), field: z.string() } }, (args) => result(() => client.related(args)));
server.registerTool("remold_today", { description: "Show due tasks and quiet opportunities for today.", inputSchema: {} }, () => result(() => client.today()));
const changeShape = { action: z.enum(["create", "update", "delete"]), object: z.string().optional(), record: z.string().optional(), values: z.record(z.string(), z.unknown()).optional(), reason: z.string() };
server.registerTool("remold_propose_change", { description: "Propose a CRM change for a person to review and apply.", inputSchema: { ...changeShape, inboxId: z.string().optional() } }, (args) => result(() => client.propose(args)));
server.registerTool("remold_apply_change", { description: "Apply a granted CRM change immediately. Use a proposal when no grant exists.", inputSchema: changeShape }, (args) => result(() => client.change(args)));
server.registerTool("remold_list_suggestions", { description: "List agent suggestions in this organisation.", inputSchema: { status: z.enum(["pending", "applied", "dismissed", "conflicted"]).optional() } }, (args) => result(() => client.listSuggestions(args)));
const fieldShape = { key: z.string().describe("camelCase, starting with a lowercase letter"), label: z.string(), type: z.enum(["text", "number", "select", "date", "boolean", "lookup", "links"]), options: z.array(z.object({ id: z.string(), label: z.string(), color: z.string().optional() })).optional().describe("select only"), target: z.string().optional().describe("object key a lookup or links field points to"), withTime: z.boolean().optional().describe("date only"), required: z.boolean().optional(), indexed: z.boolean().optional().describe("false for a text field nobody sorts or filters by, such as notes; saves an index slot") };
server.registerTool("remold_propose_shape", { description: "Propose a change to the CRM's shape for an admin to apply. addObject: key, label, labelPlural and up to 12 fields. addField: object plus the field's key, label, type. addOptions: object, field and the full option list (existing options unchanged, new ones added). relabel: object, optional field, label, and labelPlural for an object. retireField and restoreField: object and field (values are kept; standard fields features rely on cannot be retired). reorderFields: object and order, every live field key. reorderObjects: order, every object key not archived. reorderOptions: object, field and order, every option id. archiveObject and unarchiveObject: a custom object (hidden from navigation, search and remold_objects; records and links are kept). setTitleField: object and a text field. Nothing is ever deleted. Needs an admin agent.", inputSchema: { kind: z.enum(["addObject", "addField", "addOptions", "relabel", "retireField", "restoreField", "reorderFields", "reorderObjects", "reorderOptions", "archiveObject", "unarchiveObject", "setTitleField"]), reason: z.string(), object: z.string().optional(), field: z.string().optional(), key: z.string().optional(), label: z.string().optional(), labelPlural: z.string().optional(), icon: z.string().optional(), type: fieldShape.type.optional(), options: fieldShape.options, target: fieldShape.target, withTime: fieldShape.withTime, required: fieldShape.required, indexed: fieldShape.indexed, order: z.array(z.string()).optional().describe("keys or option ids in the new order"), fields: z.array(z.object(fieldShape)).max(12).optional() } }, (args) => result(() => client.proposeShape(args)));
const blueprintShape = z.object({ version: z.literal(1), name: z.string(), description: z.string().optional(), changes: z.array(z.record(z.string(), z.unknown())).describe("in order; each is a remold_propose_shape body without reason: addObject, addField, addOptions (only the options to add), relabel, reorderFields, reorderObjects, reorderOptions, archiveObject, setTitleField, retireField. Objects are named by key; a field may target an object added by this blueprint"), records: z.array(z.object({ object: z.string(), values: z.record(z.string(), z.unknown()) })).optional().describe("up to 50 starter records, by field key; lookups name a record by title. Created only if the person applying ticks the box") });
server.registerTool("remold_blueprints", { description: "List the built-in blueprints (Service business, Agency or consulting, Creator or coach, Local retail or maker) as full JSON, to adapt before proposing one with remold_propose_blueprint.", inputSchema: {} }, () => result(() => client.blueprints()));
server.registerTool("remold_export_blueprint", { description: "Export this workspace's shape (objects, fields, options, order; no records) as a blueprint, limited to what this agent can read.", inputSchema: {} }, () => result(() => client.currentBlueprint()));
server.registerTool("remold_propose_blueprint", { description: "Propose a whole reshaping (for example 'make this a repair-shop CRM') as one blueprint an admin reviews and applies all at once. It is checked in full now, against the workspace as it is: slot capacity across every change, key collisions and references. Needs an admin agent that can read every object.", inputSchema: { blueprint: blueprintShape, reason: z.string() } }, (args) => result(() => client.proposeBlueprint(args)));
server.registerTool("remold_shape_proposals", { description: "List this agent's own shape proposals and what became of them. Applied ones name the object and fields created; failed ones say why.", inputSchema: { status: z.enum(["pending", "applied", "dismissed", "failed"]).optional() } }, (args) => result(() => client.shapeProposals(args)));
server.registerTool("remold_inbox", { description: "List shared inbox work. Start here before other CRM work.", inputSchema: { status: z.enum(["pending", "resolved"]).optional() } }, (args) => result(() => client.inbox(args)));
server.registerTool("remold_inbox_add", { description: "Add a workspace note visible to its author and unrestricted workspace members.", inputSchema: { text: z.string(), source: z.string().optional() } }, (args) => result(() => client.inboxAdd(args)));
server.registerTool("remold_inbox_resolve", { description: "Resolve a shared inbox item, optionally linking its suggestion or record.", inputSchema: { id: z.string(), note: z.string().optional(), suggestionId: z.string().optional(), recordId: z.string().optional() } }, (args) => result(() => client.inboxResolve(args)));
server.registerTool("remold_campaign_report", { description: "Show a campaign's emails with status, what blocks sending, counts and rates, and each recipient's status, opens, clicks and replies.", inputSchema: { idOrRef: z.string() } }, (args) => result(() => client.campaignReport(args.idOrRef)));
server.registerTool("remold_email_preview", { description: "Render an email record for one person (or the first recipient), and list who would get it now and who is left out and why.", inputSchema: { idOrRef: z.string(), person: z.string().optional() } }, (args) => result(() => client.emailPreview(args)));
server.registerTool("remold_mark_replied", { description: "Mark a campaign send as replied, by its sendId from the campaign report. Replied people get no more follow-ups.", inputSchema: { sendId: z.string() } }, (args) => result(() => client.markReplied(args.sendId)));
await server.connect(new StdioServerTransport());
