#!/usr/bin/env node
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { z } from "zod";
import { RemoldClient, RemoldError } from "./client.js";

declare const process: { env: Record<string, string | undefined>; exit(code: number): never; };
const url = process.env.REMOLD_URL, key = process.env.REMOLD_KEY;
if (!url || !key) { console.error("REMOLD_URL and REMOLD_KEY are required"); process.exit(1); }
const client = new RemoldClient({ url, key });
const server = new McpServer({ name: "remold", version: "0.0.0" }, { instructions: "Remold is the team's CRM, and it is meant to be reshaped to fit how the team works. Records are named by a three-word code like brisk-ember-oyster; use codes or ids when you refer to one. Start with remold_inbox: pending items are work left for you. Prefer remold_propose_change; a person applies it. For many records at once (cleanups, stage moves, adding people to a campaign) use one remold_propose_batch instead of many proposals. remold_apply_change only works for actions the team granted you. When the work needs a field, object or select option that does not exist, check remold_objects, then propose it with remold_propose_shape and say why. Once remold_shape_proposals shows it applied, use it. Email campaigns: create a campaign record (channel email), link people in its people field (CSV import adds many), then draft email records (subject, body, campaign, status draft; merge tags {{firstName|there}}, {{name}}, {{company}}) and follow-ups (followsUp the earlier email, waitDays, sendTo notOpened, notClicked or notReplied). Check them with remold_email_preview. You cannot approve an email or start a campaign: ask a person to approve each email on the campaign page and press Start campaign. You may stop an email. Later, read remold_campaign_report, use remold_mark_replied for replies you learn of elsewhere, and draft follow-ups for people who did not reply." });
const result = async (run: () => Promise<unknown>) => { try { return { content: [{ type: "text" as const, text: JSON.stringify(await run(), null, 2) }] }; } catch (error) { const item = error instanceof RemoldError ? error : new RemoldError("Something went wrong", "INTERNAL"); return { isError: true, content: [{ type: "text" as const, text: `${item.code}: ${item.message}` }] }; } };
server.registerTool("remold_me", { description: "Show the CRM organisation, this agent's grants, and pending work counts.", inputSchema: {} }, () => result(() => client.me()));
server.registerTool("remold_objects", { description: "List CRM objects and the writable fields on each object.", inputSchema: {} }, () => result(() => client.objects()));
server.registerTool("remold_list_records", { description: "List records for one object. Narrow with filters (all must match, e.g. people where company is Atlas) and one date or number range. Sort, filter and range fields must be indexed.", inputSchema: { object: z.string(), cursor: z.string().optional(), limit: z.number().int().optional(), sort: z.object({ field: z.string(), direction: z.enum(["asc", "desc"]) }).optional(), filter: z.object({ field: z.string(), value: z.string() }).optional().describe("one filter; same as a single entry in filters"), filters: z.array(z.object({ field: z.string(), value: z.string() })).optional(), range: z.object({ field: z.string(), from: z.string().optional(), to: z.string().optional() }).optional().describe("from and to are YYYY-MM-DD or ISO times; either may be left out") } }, (args) => result(() => client.listRecords(args)));
server.registerTool("remold_get_record", { description: "Get one record and its recent audit events by record id or three-word code.", inputSchema: { idOrRef: z.string() } }, (args) => result(() => client.getRecord(args.idOrRef)));
server.registerTool("remold_search", { description: "Search record titles, optionally within one object.", inputSchema: { q: z.string(), object: z.string().optional(), limit: z.number().int().optional() } }, (args) => result(() => client.search(args)));
server.registerTool("remold_related", { description: "Find records related to a record through objectKey.fieldKey.", inputSchema: { idOrRef: z.string(), field: z.string() } }, (args) => result(() => client.related(args)));
server.registerTool("remold_today", { description: "Show due tasks and quiet opportunities for today.", inputSchema: {} }, () => result(() => client.today()));
const changeShape = { action: z.enum(["create", "update", "delete"]), object: z.string().optional(), record: z.string().optional(), values: z.record(z.string(), z.unknown()).optional(), links: z.record(z.string(), z.object({ add: z.array(z.string()).optional(), remove: z.array(z.string()).optional() })).optional().describe("links fields only: records to add or remove, applied to whatever is linked when the change lands"), reason: z.string() };
const { reason: _reason, ...itemShape } = changeShape;
server.registerTool("remold_propose_change", { description: "Propose a CRM change for a person to review and apply.", inputSchema: { ...changeShape, inboxId: z.string().optional() } }, (args) => result(() => client.propose(args)));
server.registerTool("remold_apply_change", { description: "Apply a granted CRM change immediately. Use a proposal when no grant exists.", inputSchema: changeShape }, (args) => result(() => client.change(args)));
const batchShape = { reason: z.string(), changes: z.array(z.object(itemShape)).min(1).max(1000) };
server.registerTool("remold_propose_batch", { description: "Propose up to 1000 changes with one reason, for a person to review as one card and apply together. Each change is like remold_propose_change; use links { field: { add, remove } } to add people to a campaign without replacing who is there. If any change is invalid nothing is saved and the error lists each bad change by index.", inputSchema: batchShape }, (args) => result(() => client.proposeBatch(args)));
server.registerTool("remold_apply_batch", { description: "Apply up to 1000 granted changes now, in the background. Every change needs a grant; otherwise use remold_propose_batch. Pass an idempotencyKey; calling again with the same key and changes returns the same batch and resumes it if it stopped.", inputSchema: { ...batchShape, idempotencyKey: z.string().optional() } }, (args) => result(() => client.applyBatch(args)));
server.registerTool("remold_batch_status", { description: "Show a batch you submitted: status, progress, and a page of its changes with what happened to each (applied, conflicted because the record changed since review, or failed with why).", inputSchema: { id: z.string(), cursor: z.string().optional(), limit: z.number().int().optional() } }, (args) => result(() => client.batchStatus(args)));
server.registerTool("remold_list_suggestions", { description: "List agent suggestions in this organisation.", inputSchema: { status: z.enum(["pending", "applied", "dismissed", "conflicted"]).optional() } }, (args) => result(() => client.listSuggestions(args)));
const fieldShape = { key: z.string().describe("camelCase, starting with a lowercase letter"), label: z.string(), type: z.enum(["text", "number", "select", "date", "boolean", "lookup", "links"]), options: z.array(z.object({ id: z.string(), label: z.string(), color: z.string().optional() })).optional().describe("select only"), target: z.string().optional().describe("object key a lookup or links field points to"), withTime: z.boolean().optional().describe("date only"), required: z.boolean().optional() };
server.registerTool("remold_propose_shape", { description: "Propose a change to the CRM's shape for an admin to apply. addObject: key, label, labelPlural and up to 12 fields. addField: object plus the field's key, label, type. addOptions: object, field and the full option list (existing options unchanged, new ones added). relabel: object, optional field, label, and labelPlural for an object. Needs an admin agent.", inputSchema: { kind: z.enum(["addObject", "addField", "addOptions", "relabel"]), reason: z.string(), object: z.string().optional(), field: z.string().optional(), key: z.string().optional(), label: z.string().optional(), labelPlural: z.string().optional(), icon: z.string().optional(), type: fieldShape.type.optional(), options: fieldShape.options, target: fieldShape.target, withTime: fieldShape.withTime, required: fieldShape.required, fields: z.array(z.object(fieldShape)).max(12).optional() } }, (args) => result(() => client.proposeShape(args)));
server.registerTool("remold_shape_proposals", { description: "List this agent's own shape proposals and what became of them. Applied ones name the object and fields created; failed ones say why.", inputSchema: { status: z.enum(["pending", "applied", "dismissed", "failed"]).optional() } }, (args) => result(() => client.shapeProposals(args)));
server.registerTool("remold_inbox", { description: "List shared inbox work. Start here before other CRM work.", inputSchema: { status: z.enum(["pending", "resolved"]).optional() } }, (args) => result(() => client.inbox(args)));
server.registerTool("remold_inbox_add", { description: "Add a workspace note visible to its author and unrestricted workspace members.", inputSchema: { text: z.string(), source: z.string().optional() } }, (args) => result(() => client.inboxAdd(args)));
server.registerTool("remold_inbox_resolve", { description: "Resolve a shared inbox item, optionally linking its suggestion or record.", inputSchema: { id: z.string(), note: z.string().optional(), suggestionId: z.string().optional(), recordId: z.string().optional() } }, (args) => result(() => client.inboxResolve(args)));
server.registerTool("remold_campaign_report", { description: "Show a campaign's emails with status, what blocks sending, counts and rates, and each recipient's status, opens, clicks and replies.", inputSchema: { idOrRef: z.string() } }, (args) => result(() => client.campaignReport(args.idOrRef)));
server.registerTool("remold_email_preview", { description: "Render an email record for one person (or the first recipient), and list who would get it now and who is left out and why.", inputSchema: { idOrRef: z.string(), person: z.string().optional() } }, (args) => result(() => client.emailPreview(args)));
server.registerTool("remold_mark_replied", { description: "Mark a campaign send as replied, by its sendId from the campaign report. Replied people get no more follow-ups.", inputSchema: { sendId: z.string() } }, (args) => result(() => client.markReplied(args.sendId)));
await server.connect(new StdioServerTransport());
