import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,writeFileSync,readFileSync,rmSync,existsSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {execFileSync} from 'node:child_process';
import {scope,candidateHeads,previewPlan,previewConfig,assertPreviewConfig,childEnvironment,convexEnvironment,workosChange,cleanupPlan} from '../../../../ops/previews/policy.mjs';
import {prepare} from '../../../../ops/previews/prepare.mjs';
import {load} from '../../../../ops/previews/state.mjs';
import {sealArtifact,verifyArtifact} from '../../../../ops/release/release.mjs';
const temp=mkdtempSync(join(tmpdir(),'remold-preview-iv-')),results=[];let ownership;
try{
 const checkout=join(temp,'checkout');execFileSync('git',['clone','--shared','--no-checkout',process.cwd(),checkout],{stdio:'pipe'});execFileSync('git',['checkout','--detach',candidateHeads[3]],{cwd:checkout,stdio:'pipe'});
 const output=join(temp,'prepared');prepare(checkout,3,output);const valid=load(output);assert.equal(valid.plan.sha,candidateHeads[3]);assert.equal(valid.receipt.hostedEffects,0);
 writeFileSync(join(checkout,'.env.iv'), 'SYNTHETIC_ONLY=1\n');assert.throws(()=>prepare(checkout,3,join(temp,'bad-env')),/environment|clean/);rmSync(join(checkout,'.env.iv'));assert.equal(load(output).plan.sha,candidateHeads[3]);
 const changed=join(checkout,'index.html'),saved=readFileSync(changed);writeFileSync(changed,Buffer.concat([saved,Buffer.from('<!-- independent dirty marker -->')]));assert.throws(()=>load(output));writeFileSync(changed,saved);assert.equal(load(output).plan.pr,3);
 execFileSync('git',['checkout','--detach',candidateHeads[4]],{cwd:checkout,stdio:'pipe'});assert.throws(()=>load(output));execFileSync('git',['checkout','--detach',candidateHeads[3]],{cwd:checkout,stdio:'pipe'});assert.equal(load(output).plan.pr,3);results.push('Exact clean PR3 accepted; local env/dirty source/PR4 head mismatch refused, then restored clean positive');
 const configPath=join(output,'wrangler.json'),configBytes=readFileSync(configPath);writeFileSync(configPath,JSON.stringify({...JSON.parse(configBytes),routes:[{pattern:'production.example.invalid/*'}]}));assert.throws(()=>load(output));writeFileSync(configPath,configBytes);load(output);
 for(const delta of [{vars:{UNREVIEWED:'x'}},{assets:{directory:'/tmp/other',not_found_handling:'none'}},{routes:['example.invalid/*']},{previews:{services:[{binding:'shared',service:'oldprod'}]}}])assert.throws(()=>assertPreviewConfig({...previewConfig('/tmp/synthetic-seal'),...delta}));results.push('Pinned configuration edit and unapproved route/vars/base settings refused');
 const artifact=join(temp,'artifact');mkdirSync(artifact);writeFileSync(join(artifact,'index.html'),'<main>Independent artifact</main>');writeFileSync(join(artifact,'version.json'),JSON.stringify({sha:candidateHeads[3]}));writeFileSync(join(artifact,'asset.js'),'synthetic-original');const pin=sealArtifact(artifact,{sha:candidateHeads[3]});verifyArtifact(artifact,candidateHeads[3],pin);writeFileSync(join(artifact,'asset.js'),'synthetic-changed');assert.throws(()=>verifyArtifact(artifact,candidateHeads[3],pin),/inventory/);writeFileSync(join(artifact,'asset.js'),'synthetic-original');verifyArtifact(artifact,candidateHeads[3],pin);results.push('Sealed artifact positive, changed asset refusal, exact restoration positive');
 const a=previewPlan(3,candidateHeads[3]),b=previewPlan(4,candidateHeads[4]);const wo={clientId:scope.clientId,redirectUris:['https://preserve.invalid/callback',a.callback,b.callback],corsOrigins:['https://preserve.invalid',b.origin],homepage:'https://keep.invalid',defaultRedirect:'https://keep.invalid/callback'};const added=workosChange(a,wo,'add');assert.deepEqual(added.owned,{callback:false,cors:true});const back={projectId:scope.projectId,deploymentType:'preview',kind:'cloud',isDefault:false,previewIdentifier:a.name,name:'independent-owl-901',id:901,createTime:91001,deploymentUrl:'https://independent-owl-901.convex.cloud'};const cf={id:'independent-cf-901',accountId:scope.accountId,worker:scope.worker,name:a.name};const receipt={plan:a,backend:back,backendAbsentBefore:true,cloudflare:{...cf,absentBefore:true},workosOwned:added.owned};const current={...added,corsOrigins:[...added.corsOrigins,'https://concurrent.invalid']};const planned=cleanupPlan(a,receipt,back,current,cf);assert(planned.workos.redirectUris.includes(a.callback));assert(planned.workos.redirectUris.includes(b.callback));assert(!planned.workos.corsOrigins.includes(a.origin));assert(planned.workos.corsOrigins.includes(b.origin));assert(planned.workos.corsOrigins.includes('https://concurrent.invalid'));assert.equal(planned.workos.homepage,wo.homepage);assert.equal(planned.workos.defaultRedirect,wo.defaultRedirect);
 for(const change of [{id:902},{createTime:91002},{projectId:scope.projectId+1},{previewIdentifier:b.name},{deploymentType:'prod'}])assert.throws(()=>cleanupPlan(a,receipt,{...back,...change},current,cf));assert.throws(()=>cleanupPlan(a,{...receipt,cloudflare:{...cf,absentBefore:false}},back,current,cf));assert.throws(()=>cleanupPlan(a,receipt,back,current,{...cf,id:'replaced-cf'}));results.push('Mixed pre-existing/owned WorkOS fields and concurrent additions preserved; replaced backend/frontend and foreign/prod identities refused');
 const synthetic=`preview:${scope.team}:${scope.project}|synthetic-only-token`;const env=convexEnvironment({PATH:'/bin',HOME:'/synthetic',CONVEX_OVERRIDE_ACCESS_TOKEN:'wrong',VITE_CONVEX_URL:'https://production.invalid',STRIPE_SECRET_KEY:'must-drop'},synthetic);assert.equal(env.CONVEX_DEPLOY_KEY,synthetic);assert.equal(env.CONVEX_OVERRIDE_ACCESS_TOKEN,synthetic);assert.equal(env.STRIPE_SECRET_KEY,undefined);assert.equal(env.VITE_CONVEX_URL,undefined);assert.throws(()=>convexEnvironment({},`preview:wrong:remold|synthetic`));assert.throws(()=>childEnvironment({},{CONVEX_DEPLOYMENT:'prod:synthetic'}));results.push('Only exact project preview key selects and authorizes CLI; inherited targets/secrets dropped');
 ownership=[];for(const flag of [false,undefined]){const r={...receipt};if(flag===undefined)delete r.backendAbsentBefore;else r.backendAbsentBefore=flag;let action,error;try{action=cleanupPlan(a,r,back,current,cf);}catch(e){error=e.message;}ownership.push({backendAbsentBefore:flag??'missing',refused:!!error,convexAction:action?.convex??null});}
 writeFileSync(new URL('./offline-result.json',import.meta.url),JSON.stringify({results,ownership,providerCalls:0,sourceAggregate:'d92702a0909fcbf7927b8bfa787be35f358bd3147b14bd896a9d2450217a5104'},null,2)+'\n');assert(ownership.every(x=>x.refused),'Backend cleanup must require absent-before ownership witness');console.log('PASS '+results.length+' altered groups + missing/false backend ownership refusal');
}finally{rmSync(temp,{recursive:true,force:true});}
