import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,writeFileSync,readFileSync,rmSync,cpSync,chmodSync,realpathSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {execFileSync} from 'node:child_process';
import {candidateHeads,previewPlan} from '../../../ops/previews/policy.mjs';
import {prepare} from '../../../ops/previews/prepare.mjs';
import {load,verifyCI} from '../../../ops/previews/state.mjs';
import {sealArtifact,verifyArtifact} from '../../../ops/release/release.mjs';
const temp=mkdtempSync(join(tmpdir(),'remold-preview-lifecycle-iv-')),oldPath=process.env.PATH,results={providerCalls:0};
try{
 const bin=join(temp,'bin');mkdirSync(bin);const config=join(temp,'gh.json'),calls=join(temp,'gh-calls.jsonl');const sha=candidateHeads[3];writeFileSync(join(bin,'gh'),`#!${process.execPath}\nconst fs=require('node:fs');const c=JSON.parse(fs.readFileSync(${JSON.stringify(config)}));fs.appendFileSync(${JSON.stringify(calls)},JSON.stringify(process.argv.slice(2))+'\\n');if(process.argv[2]==='run')console.log(JSON.stringify(c.ci));else if(process.argv[2]==='pr')console.log(JSON.stringify(c.pr));else process.exit(77);`);chmodSync(join(bin,'gh'),0o700);process.env.PATH=bin+':'+oldPath;
 const plan=previewPlan(3,sha),ci={headSha:sha,conclusion:'success',status:'completed',url:'https://example.invalid/synthetic-ci',event:'pull_request',workflowName:'Verify release candidate'};results.prCases=[];
 for(const pr of [{state:'OPEN',headRefOid:sha,baseRefName:'i2/preview-base-73b060d'},{state:'CLOSED',headRefOid:sha,baseRefName:'i2/preview-base-73b060d'},{state:'OPEN',headRefOid:candidateHeads[4],baseRefName:'i2/preview-base-73b060d'},{state:'OPEN',headRefOid:sha,baseRefName:'main'}]){writeFileSync(config,JSON.stringify({ci,pr}));let refused=false;try{verifyCI(plan);}catch{refused=true;}results.prCases.push({pr,refused});}
 results.ghCommands=readFileSync(calls,'utf8').trim().split('\n').map(JSON.parse);process.env.PATH=oldPath;
 const checkout=join(temp,'checkout');execFileSync('git',['clone','--shared','--no-checkout',process.cwd(),checkout],{stdio:'pipe'});execFileSync('git',['checkout','--detach',sha],{cwd:checkout,stdio:'pipe'});const original=join(temp,'original');prepare(checkout,3,original);const art=join(original,'artifact');mkdirSync(art);writeFileSync(join(art,'index.html'),'<main>Verified bytes</main>');writeFileSync(join(art,'version.json'),JSON.stringify({sha}));writeFileSync(join(art,'app.js'),'original-sealed');const pin=sealArtifact(art,{sha});const receipt=JSON.parse(readFileSync(join(original,'receipt.json')));receipt.phase='artifact-ready';receipt.artifact={sha,manifestSha256:pin,configSha256:receipt.configSha256};writeFileSync(join(original,'receipt.json'),JSON.stringify(receipt));load(original);
 const moved=join(temp,'moved');cpSync(original,moved,{recursive:true});writeFileSync(join(art,'app.js'),'different-unverified-upload-bytes');let loadRefused=false;try{load(moved);}catch{loadRefused=true;}verifyArtifact(join(moved,'artifact'),sha,pin);let uploadSealRefused=false;try{verifyArtifact(art,sha,pin);}catch{uploadSealRefused=true;}const configured=JSON.parse(readFileSync(join(moved,'wrangler.json'))).assets.directory;results.relocation={loadRefused,movedArtifactVerifies:true,configuredArtifactDoesNotVerify:uploadSealRefused,configuredEqualsVerifiedDirectory:realpathSync(configured)===realpathSync(join(moved,'artifact')),phase:JSON.parse(readFileSync(join(moved,'receipt.json'))).phase};
 writeFileSync(new URL('./lifecycle-result.json',import.meta.url),JSON.stringify(results,null,2)+'\n');assert.equal(results.prCases[0].refused,false);assert(results.prCases.slice(1).every(x=>x.refused),'Successful old CI must not permit closed/retargeted PR');assert(loadRefused,'Moved output must not verify one artifact and upload another');console.log('PASS live PR guard + canonical artifact binding');
}finally{process.env.PATH=oldPath;rmSync(temp,{recursive:true,force:true});}
