async function peerHeadroom(f,label){
 const b={...f,A:f.B};const fixed=await op(b,'iv-peer-fixed-'+label,'owner','marketing.send',6,{payload:payload('B')});await approve(b,fixed);await claim(b,fixed,'owner');
 const extra=await op(b,'iv-peer-extra-'+label,'owner','marketing.send',3,{payload:payload('B')});await approve(b,extra);return {b,extra};
}
for(const path of ['grant-sweep','readonly-expiry','terminal-failure','retryable-failure'])await test('Unresolved prior attempt retains shared exposure through '+path,async()=>{
 const f=seed(),g=await grant(f);const id=await op(f,'iv-async-'+path,'manager','marketing.send',7);await approve(f,id);const first=await claim(f,id),request=await consume(f,await permit(f,id,first));await call('unknown',{token:f.A.adapter,id,...first});await call('resolveUnknown',{token:f.A.adapter,id,...first,absent:true,finality:'provisional'});
 if(path==='grant-sweep')await call('revokeGrant',{token:f.A.sessions.owner,id:g});else{const retry=await claim(f,id,'manager','iv-second');const p=await permit(f,id,retry,'iv-second');if(path==='readonly-expiry'){await call('control',{token:f.A.sessions.owner,readonly:true});await wait(1500);}else{if(path==='retryable-failure'){const again=await consume(f,p);assert.equal(again.key,request.key);}await call('fail',{token:f.A.adapter,id,...retry,retryable:path==='retryable-failure'});}}
 const unresolved=await get(f,id),before=dump(f),org=before.orgs.find(x=>x._id===f.A.org);assert.equal(unresolved.state,'outcomeUnknown');assert.equal(org.reserved,7);assert.equal(org.active,1);assert.equal(org.spent,0);assert.equal(unresolved.released,false);
 const {b,extra}=await peerHeadroom(f,path);await assert.rejects(claim(b,extra,'owner'),/global budget/);assert.equal(dump(f).budgets[0].reserved,13);
 const r=accept(request);await Promise.all([finish(f,id,first,r,5),finish(f,id,first,r,5)]);const final=await get(f,id),data=dump(f),a=data.orgs.find(x=>x._id===f.A.org);assert.equal(final.state,'confirmed');assert.equal(final.late,true);assert.equal(final.receipts.length,1);assert.equal(a.spent,5);assert.equal(a.reserved,0);assert.equal(a.active,0);assert.equal(a.anomaly,undefined);assert.equal(data.budgets[0].reserved,6);assert.equal(data.budgets[0].spent,5);await claim(b,extra,'owner');assert.equal(dump(f).budgets[0].reserved,9);
});
await test('Cancelled confirmed missing usage retains global reservation until a concurrent duplicate settlement',async()=>{
 const f=seed();await grant(f);const id=await op(f,'iv-missing-cancel-r3','manager','marketing.send',7);await approve(f,id);const c=await claim(f,id),r=accept(await consume(f,await permit(f,id,c)));await call('reconcile',{token:f.A.adapter,id,...c,providerRef:r.ref});
 await Promise.all([call('cancel',{token:f.A.sessions.owner,id}),call('cancel',{token:f.A.sessions.owner,id})]);const {b,extra}=await peerHeadroom(f,'missing-cancel');await assert.rejects(claim(b,extra,'owner'),/global budget/);let a=dump(f).orgs.find(x=>x._id===f.A.org);assert.equal(a.reserved,7);assert.equal(a.active,1);assert.equal(a.missingUsage,true);assert.equal((await get(f,id)).released,false);
 await Promise.all([finish(f,id,c,r,5),finish(f,id,c,r,5)]);a=dump(f).orgs.find(x=>x._id===f.A.org);assert.equal(a.spent,5);assert.equal(a.reserved,0);assert.equal(a.active,0);assert.equal(a.missingUsage,false);assert.equal((await get(f,id)).state,'confirmed');await claim(b,extra,'owner');assert.equal(dump(f).budgets[0].spent+dump(f).budgets[0].reserved,14);
});
for(const cancellation of ['none','before-unknown','after-unknown'])await test('Unconsumed unknown recovers autonomously with cancellation '+cancellation,async()=>{
 const f=seed();await grant(f);const id=await op(f,'iv-unused-'+cancellation,'manager','marketing.send',2);await approve(f,id);const c=await claim(f,id);await permit(f,id,c);
 if(cancellation==='before-unknown')await call('cancel',{token:f.A.sessions.owner,id});await call('unknown',{token:f.A.adapter,id,...c});if(cancellation==='after-unknown')await call('cancel',{token:f.A.sessions.owner,id});await wait(1600);
 const result=await get(f,id),org=dump(f).orgs.find(x=>x._id===f.A.org);assert.equal(result.state,cancellation==='none'?'queued':'cancelled');assert.deepEqual(result.consumedPermits,[]);assert.deepEqual(result.receipts,[]);assert.equal(org.spent,0);assert.equal(org.reserved,cancellation==='none'?2:0);assert.equal(org.active,cancellation==='none'?1:0);assert.ok(dump(f).events.some(e=>e.resource===id&&e.actor==='system-expiry'));if(cancellation==='none')assert.ok(await claim(f,id,'manager','recovered'));
});
for(const variant of ['one-step','delayed-usage','cancelled-delayed'])await test('Accepted overrun remains confirmed for '+variant,async()=>{
 const f=seed();await grant(f);const id=await op(f,'iv-accepted-overrun-'+variant,'manager','marketing.send',2);await approve(f,id);const c=await claim(f,id),r=accept(await consume(f,await permit(f,id,c)));
 if(variant!=='one-step')await call('reconcile',{token:f.A.adapter,id,...c,providerRef:r.ref});if(variant==='cancelled-delayed')await call('cancel',{token:f.A.sessions.owner,id});await finish(f,id,c,r,4);await finish(f,id,c,r,4);const result=await get(f,id),org=dump(f).orgs.find(x=>x._id===f.A.org);assert.equal(result.state,'confirmed');assert.equal(result.overrun,true);assert.equal(result.usage,4);assert.equal(org.spent,4);assert.equal(org.reserved,0);assert.equal(org.active,0);assert.equal(org.anomaly,'usageOverrun');assert.equal(org.missingUsage,false);
 const fresh=await op(f,'iv-overrun-hold-'+variant,'owner');await approve(f,fresh);await assert.rejects(claim(f,fresh,'owner'),/anomaly hold/);
});
await test('Exactly exhausted multi-step continuation refuses more work and releases capacity once',async()=>{
 const f=seed();await grant(f,'manager','model.call');const id=await op(f,'iv-exhaust-multi','manager','model.call',5);await approve(f,id);const a=await claim(f,id),r1=accept(await consume(f,await permit(f,id,a)));await finish(f,id,a,r1,3,true);const b=await claim(f,id),p2=await permit(f,id,b);assert.equal(p2.maxUnits,2);const r2=accept(await consume(f,p2));const result=await finish(f,id,b,r2,2,true);assert.equal(result.continuationRefused,true);await finish(f,id,b,r2,2,true);const operation=await get(f,id),org=dump(f).orgs.find(x=>x._id===f.A.org);assert.equal(operation.state,'confirmed');assert.equal(operation.step,2);assert.equal(operation.receipts.length,2);assert.equal(operation.released,true);assert.equal(org.spent,5);assert.equal(org.reserved,0);assert.equal(org.active,0);await assert.rejects(claim(f,id),/released/);
 const next=await op(f,'iv-after-exhaust','owner','marketing.send',2);await approve(f,next);await claim(f,next,'owner');assert.equal(dump(f).orgs.find(x=>x._id===f.A.org).active,1);
});
await test('New binding recipient suppression persists without prior row and survives duplicate/out-of-order callback',async()=>{
 const f=seed(),recipient='iv-brand-new-recipient-317';const intent=await call('provision',{token:f.A.sessions.owner,binding:f.A.binding,intent:'iv-new-contact',remove:false}),binding=await call('bind',{token:f.A.adapter,intent,kind:'contact',externalId:'iv-new-external317',local:recipient});
 const cb=(version,state,eventId)=>call('callback',{token:f.A.adapter,binding,eventId,body:JSON.stringify({version,state,channel:'email',purpose:'marketing'})});await cb(73,'suppressed','iv-new-suppression');await cb(73,'suppressed','iv-new-suppression');await cb(72,'subscribed','iv-old-optin');const rows=dump(f).consent.filter(c=>c.org===f.A.org&&c.recipient===recipient);assert.equal(rows.length,1);assert.equal(rows[0].suppressed,true);assert.equal(rows[0].version,1);
 await grant(f,'manager','marketing.send',{scope:bindingScope(f.A,{bindings:[binding]})});const id=await op(f,'iv-new-suppressed','manager','marketing.send',1,{binding,payload:{...payload(),audience:[recipient]}});await approve(f,id);await assert.rejects(claim(f,id),/consent denied/);assert.equal(dump(f).consent.filter(c=>c.org===f.B.org&&c.recipient===recipient).length,0);
});
await test('Concurrent old receipt and retry failure preserve accepted truth and exact budget once',async()=>{
 const f=seed();await grant(f);const id=await op(f,'iv-outcome-race','manager','marketing.send',4);await approve(f,id);const old=await claim(f,id),request=await consume(f,await permit(f,id,old));await call('unknown',{token:f.A.adapter,id,...old});await call('resolveUnknown',{token:f.A.adapter,id,...old,absent:true,finality:'provisional'});const retry=await claim(f,id);await permit(f,id,retry);const r=accept(request);
 const outcomes=await Promise.allSettled([finish(f,id,old,r,3),call('fail',{token:f.A.adapter,id,...retry,retryable:false})]);assert.equal(outcomes[0].status,'fulfilled');if(outcomes[1].status==='rejected')assert.match(String(outcomes[1].reason),/stale failure/);const result=await get(f,id),org=dump(f).orgs.find(x=>x._id===f.A.org);assert.equal(result.state,'confirmed');assert.equal(result.receipts.length,1);assert.equal(org.spent,3);assert.equal(org.reserved,0);assert.equal(org.active,0);assert.equal(org.anomaly,undefined);
});
