import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {docker,directory,prefix} from './runtime.mjs';
import {mautic} from './api.mjs';
import {authority} from './authority.mjs';
const f=JSON.parse(readFileSync(directory+'private/native-fixture.json')),config=JSON.parse(readFileSync(directory+'private/bridge-config.json'));
const cli=(...args)=>docker(['exec','--user','www-data',prefix+'-web-a','php','/var/www/html/bin/console',...args]);
const status=async()=>{const r=await fetch('http://127.0.0.1:3542/status',{method:'POST',headers:{'x-remold-key':config.bridgeKey},body:'{}'});assert.equal(r.status,200);const v=await r.json();return {...v,intents:v.intents.filter(x=>x.occurrence.lead===f.contact)};};
const before=await status();assert.equal(before.intents.length,2,'Run branch-replay first');
await mautic('/campaigns/'+f.campaign+'/contact/'+f.contact+'/remove','POST',{});
await mautic('/campaigns/'+f.campaign+'/contact/'+f.contact+'/add','POST',{});
cli('mautic:campaigns:trigger','-i',String(f.campaign));
const after=await status(),newIntents=after.intents.filter(x=>!before.intents.some(old=>old.intent===x.intent));
writeFileSync(directory+'evidence/reentry-observed.json',JSON.stringify({level:'SERVICE native campaign remove/readd',before:before.intents.map(x=>x.occurrence),after:after.intents.map(x=>x.occurrence),newIntentCount:newIntents.length},null,2)+'\n');
assert.equal(newIntents.length,1,'Re-entry starts one new native send, not the old open branch');
const next=newIntents[0];assert.equal(next.occurrence.rotation,2);assert.ok(!before.intents.some(x=>x.occurrence.log===next.occurrence.log));
assert.equal(next.occurrence.event,before.intents[0].occurrence.event);
authority('harness:approve',{token:config.fixture.A.sessions.owner,id:next.operation,expires:Date.now()+3600000});
cli('messenger:consume','email','--limit=10','--time-limit=3','--no-interaction');
for(let n=0;n<3;n++)cli('mautic:campaigns:trigger','-i',String(f.campaign));
const final=await status();assert.equal(final.intents.length,3);assert.equal(final.deliveries.filter(x=>x.id===next.intent).length,1);
writeFileSync(directory+'evidence/reentry.json',JSON.stringify({level:'SERVICE explicit driver-approved re-entry, local sink only',checks:{rotationAdvanced:2,newLogIdentity:true,newIntentIdentity:true,oldOpenDidNotTriggerSecondBranch:true,oneReentryReceipt:true,extraCronPasses:3}},null,2)+'\n');
console.log('PASS native re-entry advances rotation and creates one distinct occurrence; old open does not fire its new branch.');
